using System;
using System.Collections.Generic;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Comments;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.DefaultStyles;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableCellPropertiesElements;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableRowPropertiesElements;
using Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Vector;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing;
using Telerik.Windows.Documents.Utilities;

namespace Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model
{
	static class DocxElementsFactory
	{
		static DocxElementsFactory()
		{
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("body", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.BodyElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("p", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.ParagraphElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("r", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.RunElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("t", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TextElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("instrText", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.InstructionTextElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tab", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TabElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tbl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TableElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TableRowElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tc", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TableCellElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("fldChar", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.FieldCharacterElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("hyperlink", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.HyperlinkElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("fldSimple", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.SimpleFieldElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("bookmarkStart", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.BookmarkStartElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("bookmarkEnd", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.BookmarkEndElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("br", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.BreakElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("commentRangeStart", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.CommentRangeStartElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("commentRangeEnd", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.CommentRangeEndElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("commentReference", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.CommentReferenceElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("permStart", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.PermissionStartElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("permEnd", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.PermissionEndElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("comment", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Comments.CommentElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("abstractNum", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.AbstractListElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("abstractNumId", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.AbstractListIdElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("num", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.NumberedListElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("lvl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.ListLevelElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("lvlText", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.NumberTextFormatElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("multiLevelType", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.MultiLevelTypeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("numFmt", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.NumberingStyleElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("numStyleLink", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.NumStyleLinkElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("styleLink", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.StyleLinkElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("start", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.StartIndexElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("lvlRestart", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.RestartAfterLevelElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("isLgl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.IsLegalElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("lvlJc", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.AlignmentElement(pm, "lvlJc"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("startOverride", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.StartIndexOverrideElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("lvlOverride", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Lists.ListLevelOverrideElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("docDefaults", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.DefaultStyles.DocumentDefaultStylesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pPrDefault", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.DefaultStyles.ParagraphDefaultPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("rPrDefault", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.DefaultStyles.RunDefaultPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("style", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StyleElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("name", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements.StyleNameElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("qFormat", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements.IsPrimaryElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("next", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements.NextStyleIdElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("link", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements.LinkedStyleIdElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("uiPriority", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements.UIPriorityElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("basedOn", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StylePropertiesElements.BasedOnStyleIdElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("rPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.RunPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.ParagraphPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("trPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TableRowPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TablePropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tcPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TableCellPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("sectPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.SectionPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("shd", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ShadingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("jc", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.AlignmentElement(pm, "jc"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("left", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "left"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("top", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "top"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("right", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "right"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("bottom", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "bottom"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("between", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "between"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("insideH", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "insideH"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("insideV", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "insideV"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tl2br", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "tl2br"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tr2bl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.BorderElement(pm, "tr2bl"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("vAlign", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.VerticalAlignmentElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("b", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.BoldElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("vertAlign", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.BaselineAlignmentElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("sz", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.FontSizeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("i", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.ItalicElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("rFonts", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.FontElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("color", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.ForegroundColorElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("highlight", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.HighlightElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("strike", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.StrikethroughElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("u", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.RunPropertiesElements.UnderlineElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("rtl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.FlowDirectionElement(pm, "rtl"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("rStyle", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StyleIdElement(pm, "rStyle"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("bidi", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.FlowDirectionElement(pm, "bidi"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("keepLines", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.KeepOnOnePageElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("keepNext", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.KeepWithNextParagraphElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("kinsoku", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.ApplyEastAsianLineBreakingRulesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pageBreakBefore", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.PageBreakBeforeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("contextualSpacing", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.ContextualSpacingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("mirrorIndents", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.MirrorIndentsElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("ind", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.IndentationElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("overflowPunct", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.AllowOverflowPunctuationElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("numPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.NumberingPropertiesElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("numId", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.ListIdElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("ilvl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.ParagraphListLevel(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("spacing", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.SpacingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("outlineLvl", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.OutlineLevelElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pBdr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.ParagraphBordersElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pStyle", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StyleIdElement(pm, "pStyle"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tabs", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.ParagraphPropertiesElements.TabStopsElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblBorders", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements.TableBordersElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblCellSpacing", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableWidthElement(pm, "tblCellSpacing"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblInd", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableWidthElement(pm, "tblInd"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblCellMar", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableCellPaddingElement(pm, "tblCellMar"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblStyleRowBandSize", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements.RowBandingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblStyleColBandSize", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements.ColumnBandingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblW", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableWidthElement(pm, "tblW"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("bidiVisual", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.FlowDirectionElement(pm, "bidiVisual"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblLayout", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements.TableLayoutTypeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblLook", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements.TableLooksElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblOverlap", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TablePropertiesElements.OverlapElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblStyle", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.StyleIdElement(pm, "tblStyle"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("headerReference", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.HeaderReferenceElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("footerReference", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.FooterReferenceElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("titlePg", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TitlePageElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("type", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.SectionTypeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pgMar", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.PageMarginsElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pgSz", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.PageSizeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pgNumType", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.PageNumberingSettingsElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tblHeader", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableRowPropertiesElements.RepeatOnEveryPageElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("cantSplit", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableRowPropertiesElements.CanSplitElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("trHeight", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableRowPropertiesElements.TableRowHeightElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("gridSpan", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.GridSpanElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("vMerge", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.VerticalMergeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("hMerge", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.HorizontalMergeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tcBorders", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableCellPropertiesElements.TableCellBordersElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tcMar", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableCellPaddingElement(pm, "tcMar"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("hideMark", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableCellPropertiesElements.IgnoreCellMarkerInRowHeightCalculationElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("noWrap", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableCellPropertiesElements.CanWrapContentElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("tcW", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Styles.TableWidthElement(pm, "tcW"));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("textDirection", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.TextDirectionElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("extent", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.SizeElement(pm, "extent", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.WordprocessingDrawingMLNamespace));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("drawing", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.DrawingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("inline", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.InlineElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("anchor", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.AnchorElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("docPr", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.NonVisualDrawingPropertiesElement(pm, "docPr", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.WordprocessingDrawingMLNamespace));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("simplePos", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.OffsetElement(pm, "simplePos", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.WordprocessingDrawingMLNamespace));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("positionH", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.HorizontalPositionElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("positionV", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.VerticalPositionElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("posOffset", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.OneDimentionOffsetElement(pm, "posOffset", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.WordprocessingDrawingMLNamespace));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("wrapNone", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.WrapNoneElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("wrapSquare", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.WrapSquareElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("wrapTopAndBottom", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.WrapTopAndBottomElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("blipFill", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.PictureFillElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("effectExtent", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Drawing.EffectExtentElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("pict", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.VmlContainerElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("shape", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Vector.ShapeElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("imagedata", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Vector.ImageDataElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("fill", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Vector.FillElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("textpath", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Vector.TextpathElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("evenAndOddHeaders", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.EvenAndOddHeadersFootersElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("updateFields", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.UpdateFieldsElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("compat", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.CompatibilityElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("compatSetting", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.CompatibilitySettingElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("docVars", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.DocumentVariableCollectionElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("docVar", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.DocumentVariableElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("documentProtection", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.DocumentProtectionElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("defaultTabStop", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Settings.DefaultTabStopWidthElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("sdt", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.StructuredDocumentTagElement(pm));
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.RegisterFactoryMethod("sdtContent", (global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager pm) => new global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.Elements.Document.StructuredDocumentTagContentElement(pm));
		}

		public static global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase CreateInstance(string elementName, global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager partsManager)
		{
			global::Telerik.Windows.Documents.Utilities.Guard.ThrowExceptionIfNullOrEmpty(elementName, "elementName");
			global::Telerik.Windows.Documents.Utilities.Guard.ThrowExceptionIfNull<global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager>(partsManager, "partsManager");
			return global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.elementNameToFactoryMethod[elementName](partsManager);
		}

		public static bool CanCreateInstance(string elementName)
		{
			global::Telerik.Windows.Documents.Utilities.Guard.ThrowExceptionIfNullOrEmpty(elementName, "elementName");
			return global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.elementNameToFactoryMethod.ContainsKey(elementName);
		}

		private static void RegisterFactoryMethod(string elementName, global::System.Func<global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase> factoryMethod)
		{
			global::Telerik.Windows.Documents.Utilities.Guard.ThrowExceptionIfNullOrEmpty(elementName, "elementName");
			global::Telerik.Windows.Documents.Utilities.Guard.ThrowExceptionIfNull<global::System.Func<global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase>>(factoryMethod, "factoryMethod");
			global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxElementsFactory.elementNameToFactoryMethod.Add(elementName, factoryMethod);
		}

		private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Func<global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase>> elementNameToFactoryMethod = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::Telerik.Windows.Documents.Flow.FormatProviders.Docx.Model.DocxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase>>();
	}
}
