using System;
using System.Collections.Generic;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common;
using Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing;
using Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Common;
using Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing;
using Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings;
using Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet;
using Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks;
using Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets;
using Telerik.Windows.Documents.Spreadsheet.Utilities;

namespace Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model
{
	static class XlsxElementsFactory
	{
		static XlsxElementsFactory()
		{
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("si", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings.StringItemElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("t", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings.TextElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("r", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings.RichTextRunElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("x:t", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings.TextElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("x:r", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings.RichTextRunElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("is", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.RichTextInlineElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("u", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Common.UnderlineElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("vertAlign", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.SharedStrings.VerticalAlignmentElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("alignment", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.AlignmentElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("protection", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.ProtectionElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("bgColor", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.BackgroundColorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("b", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.BoldElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("border", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.BorderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("left", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.LeftBorderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("right", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.RightBorderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("top", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.TopBorderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("bottom", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.BottomBorderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("diagonal", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.DiagonalBorderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("borders", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.BordersElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("color", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Common.ColorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cellXfs", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.CellFormatsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("xf", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FormatElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cellStyle", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.CellStyleElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cellStyleXfs", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.CellStyleFormatsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cellStyles", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.CellStylesElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("indexedColors", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.IndexedColorsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("gradientFill", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.GradientFillElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("patternFill", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.PatternFillElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("fill", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FillElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("fills", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FillsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("name", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FontNameElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("family", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FontFamilyElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("i", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.ItalicElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sz", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FontSizeElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("scheme", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.SchemeElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("font", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FontElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("fonts", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.FontsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("fgColor", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.ForegroundColorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("stop", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.StopElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("rgbColor", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.RgbColorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("numFmt", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.NumberFormatElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("x:numFmt", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.NumberFormatElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("numFmts", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.NumberFormatsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("colors", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.ColorsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheet", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.SheetElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheets", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.SheetsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("bookViews", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.BookViewsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("workbookView", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.WorkbookViewElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("f", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FormulaElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("x:f", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FormulaElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("definedNames", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.DefinedNamesElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("definedName", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.DefinedNameElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("hyperlinks", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.HyperlinksElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("hyperlink", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.HyperlinkElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("v", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.CellValueElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("x:v", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.CellValueElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("col", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.ColumnElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cols", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.ColumnsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("mergeCell", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.MergedCellElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("mergeCells", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.MergedCellsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("row", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.RowElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("pane", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.PaneElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("selection", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SelectionElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheetView", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SheetViewElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheetViews", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SheetViewsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheetData", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SheetDataElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheetProtection", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SheetProtectionElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("workbookProtection", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Workbooks.WorkbookProtectionElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheetFormatPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SheetFormatPropertiesElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("c", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.CellElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dxfs", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.DifferentialFormatsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dxf", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.StyleSheet.DifferentialFormatElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dimension", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.DimensionElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sqref", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SqRefElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sheetPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SheetPropertiesElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("outlinePr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.OutlinePropertiesElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("pageSetUpPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.PageSetUpPropertiesElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("printOptions", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.PrintOptionsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("pageMargins", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.PageMarginsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("pageSetup", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.PageSetupElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("rowBreaks", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.RowBreaksElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("colBreaks", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.ColumnBreaksElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("brk", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.BreakElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("headerFooter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.HeaderFooterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("oddHeader", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.OddHeaderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("oddFooter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.OddFooterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("evenHeader", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.EvenHeaderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("evenFooter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.EvenFooterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("firstHeader", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FirstHeaderElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("firstFooter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FirstFooterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("autoFilter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.AutoFilterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("filterColumn", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FilterColumnElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("filters", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FiltersElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("filter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FilterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dateGroupItem", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.DateGroupItemElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("customFilters", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.CustomFiltersElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("customFilter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.CustomFilterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("top10", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.Top10FilterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dynamicFilter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.DynamicFilterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("colorFilter", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.ColorFilterElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sortState", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SortStateElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("sortCondition", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.SortConditionElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("colOff", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.OneDimentionOffsetElement(pm, "colOff", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("rowOff", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.OneDimentionOffsetElement(pm, "rowOff", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("from", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.MarkerElement(pm, "from"));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("to", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.MarkerElement(pm, "to"));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("absoluteAnchor", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.AbsoluteAnchorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("pos", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.OffsetElement(pm, "pos", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("oneCellAnchor", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.OneCellAnchorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("twoCellAnchor", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.TwoCellAnchorElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("drawing", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.DrawingElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("pic", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.PictureElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("clientData", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.ClientDataElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("blipFill", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Drawing.BlipFillElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("spPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.ShapePropertiesElement(pm, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("nvPicPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.NonVisualPicturePropertiesElement(pm, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cNvPicPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.NonVisualPictureDrawingPropertiesElement(pm, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cNvPr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Common.NonVisualDrawingPropertiesElement(pm, "cNvPr", global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("graphicFrame", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.GraphicFrameElement(pm, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("nvGraphicFramePr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.NonVisualGraphicFramePropertiesElement(pm, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("cNvGraphicFramePr", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.Drawing.NonVisualGraphicFrameDrawingPropertiesElement(pm, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.OpenXmlNamespaces.SpreadsheetDrawingMLNamespace));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dataValidations", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.DataValidationsElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("dataValidation", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.DataValidationElement(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("formula1", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.Formula1Element(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("formula2", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.Formula2Element(pm));
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.RegisterFactoryMethod("extLst", (global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager pm) => new global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.Elements.Worksheets.FutureFeatureDataStorageAreaElement(pm));
		}

		public static global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase CreateInstance(string elementName, global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager partsManager)
		{
			global::Telerik.Windows.Documents.Spreadsheet.Utilities.Guard.ThrowExceptionIfNullOrEmpty(elementName, "elementName");
			global::Telerik.Windows.Documents.Spreadsheet.Utilities.Guard.ThrowExceptionIfNull<global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager>(partsManager, "partsManager");
			return global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.elementNameToFactoryMethod[elementName](partsManager);
		}

		public static bool CanCreateInstance(string elementName)
		{
			global::Telerik.Windows.Documents.Spreadsheet.Utilities.Guard.ThrowExceptionIfNullOrEmpty(elementName, "elementName");
			return global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.elementNameToFactoryMethod.ContainsKey(elementName);
		}

		private static void RegisterFactoryMethod(string elementName, global::System.Func<global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase> factoryMethod)
		{
			global::Telerik.Windows.Documents.Spreadsheet.Utilities.Guard.ThrowExceptionIfNullOrEmpty(elementName, "elementName");
			global::Telerik.Windows.Documents.Spreadsheet.Utilities.Guard.ThrowExceptionIfNull<global::System.Func<global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase>>(factoryMethod, "factoryMethod");
			global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxElementsFactory.elementNameToFactoryMethod.Add(elementName, factoryMethod);
		}

		private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Func<global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase>> elementNameToFactoryMethod = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.Xlsx.Model.XlsxPartsManager, global::Telerik.Windows.Documents.FormatProviders.OpenXml.Model.Elements.OpenXmlElementBase>>();
	}
}
