using System;

namespace Telerik.Windows.Documents.Flow.Model.Lists
{
	public enum NumberingStyle
	{
		Decimal,
		UpperRoman,
		LowerRoman,
		UpperLetter,
		LowerLetter,
		Ordinal,
		CardinalText,
		OrdinalText,
		Hex,
		Chicago,
		IdeographDigital,
		JapaneseCounting,
		Aiueo,
		Iroha,
		DecimalFullWidth,
		DecimalHalfWidth,
		JapaneseLegal,
		JapaneseDigitalTenThousand,
		DecimalEnclosedCircle,
		DecimalFullWidth2,
		AiueoFullWidth,
		IrohaFullWidth,
		DecimalZero,
		Bullet,
		Ganada,
		Chosung,
		DecimalEnclosedFullStop,
		DecimalEnclosedParent,
		DecimalEnclosedCircleChinese,
		IdeographEnclosedCircle,
		IdeographTraditional,
		IdeographZodiac,
		IdeographZodiacTraditional,
		TaiwaneseCounting,
		IdeographLegalTraditional,
		TaiwaneseCountingThousand,
		TaiwaneseDigital,
		ChineseCounting,
		ChineseLegalSimplified,
		ChineseCountingThousand,
		KoreanDigital = 41,
		KoreanCounting,
		KoreanLegal,
		KoreanDigital2,
		VietnameseCounting = 56,
		RussianLower = 58,
		RussianUpper,
		None = 255,
		NumberInDash = 57,
		Hebrew1 = 45,
		Hebrew2 = 47,
		ArabicAlpha = 46,
		ArabicAbjad = 48,
		HindiVowels,
		HindiConsonants,
		HindiNumbers,
		HindiCounting,
		ThaiLetters,
		ThaiNumbers,
		ThaiCounting,
		BahtText = 0,
		DollarText = 0,
		Custom = 0
	}
}
