using System;
using System.Collections.Generic;

namespace Telerik.Windows.Documents.Core.Fonts.OpenType.Tables
{
	abstract class Post : TrueTypeTableBase
	{
		static Post()
		{
			Post.Initialize();
		}

		public Post(OpenTypeFontSourceBase fontSource)
			: base(fontSource)
		{
		}

		internal override uint Tag
		{
			get
			{
				return Tags.POST_TABLE;
			}
		}

		public double ItalicAngle { get; set; }

		public double UnderlinePosition { get; set; }

		public double UnderlineThickness { get; set; }

		public static Post ReadPostTable(OpenTypeFontSourceBase fontSource, OpenTypeFontReader reader)
		{
			float num = reader.ReadFixed();
			Post post;
			if (num == 1f)
			{
				post = new PostFormat1(fontSource);
			}
			else if (num == 2f)
			{
				post = new PostFormat2(fontSource);
			}
			else
			{
				if (num != 3f)
				{
					return null;
				}
				post = new PostFormat3(fontSource);
			}
			post.Read(reader);
			return post;
		}

		public abstract ushort GetGlyphId(string name);

		public override void Read(OpenTypeFontReader reader)
		{
			this.ItalicAngle = (double)reader.ReadFixed();
			this.UnderlinePosition = (double)reader.ReadShort();
			this.UnderlineThickness = (double)reader.ReadShort();
			reader.ReadULong();
			reader.ReadULong();
			reader.ReadULong();
			reader.ReadULong();
			reader.ReadULong();
		}

		static void Initialize()
		{
			Post.macintoshStandardOrderGlyphIds = new Dictionary<string, ushort>();
			Post.macintoshStandardOrderGlyphIds[".notdef"] = 0;
			Post.macintoshStandardOrderGlyphIds[".null"] = 1;
			Post.macintoshStandardOrderGlyphIds["nonmarkingreturn"] = 2;
			Post.macintoshStandardOrderGlyphIds["space"] = 3;
			Post.macintoshStandardOrderGlyphIds["exclam"] = 4;
			Post.macintoshStandardOrderGlyphIds["quotedbl"] = 5;
			Post.macintoshStandardOrderGlyphIds["numbersign"] = 6;
			Post.macintoshStandardOrderGlyphIds["dollar"] = 7;
			Post.macintoshStandardOrderGlyphIds["percent"] = 8;
			Post.macintoshStandardOrderGlyphIds["ampersand"] = 9;
			Post.macintoshStandardOrderGlyphIds["quotesingle"] = 10;
			Post.macintoshStandardOrderGlyphIds["parenleft"] = 11;
			Post.macintoshStandardOrderGlyphIds["parenright"] = 12;
			Post.macintoshStandardOrderGlyphIds["asterisk"] = 13;
			Post.macintoshStandardOrderGlyphIds["plus"] = 14;
			Post.macintoshStandardOrderGlyphIds["comma"] = 15;
			Post.macintoshStandardOrderGlyphIds["hyphen"] = 16;
			Post.macintoshStandardOrderGlyphIds["period"] = 17;
			Post.macintoshStandardOrderGlyphIds["slash"] = 18;
			Post.macintoshStandardOrderGlyphIds["zero"] = 19;
			Post.macintoshStandardOrderGlyphIds["one"] = 20;
			Post.macintoshStandardOrderGlyphIds["two"] = 21;
			Post.macintoshStandardOrderGlyphIds["three"] = 22;
			Post.macintoshStandardOrderGlyphIds["four"] = 23;
			Post.macintoshStandardOrderGlyphIds["five"] = 24;
			Post.macintoshStandardOrderGlyphIds["six"] = 25;
			Post.macintoshStandardOrderGlyphIds["seven"] = 26;
			Post.macintoshStandardOrderGlyphIds["eight"] = 27;
			Post.macintoshStandardOrderGlyphIds["nine"] = 28;
			Post.macintoshStandardOrderGlyphIds["colon"] = 29;
			Post.macintoshStandardOrderGlyphIds["semicolon"] = 30;
			Post.macintoshStandardOrderGlyphIds["less"] = 31;
			Post.macintoshStandardOrderGlyphIds["equal"] = 32;
			Post.macintoshStandardOrderGlyphIds["greater"] = 33;
			Post.macintoshStandardOrderGlyphIds["question"] = 34;
			Post.macintoshStandardOrderGlyphIds["at"] = 35;
			Post.macintoshStandardOrderGlyphIds["A"] = 36;
			Post.macintoshStandardOrderGlyphIds["B"] = 37;
			Post.macintoshStandardOrderGlyphIds["C"] = 38;
			Post.macintoshStandardOrderGlyphIds["D"] = 39;
			Post.macintoshStandardOrderGlyphIds["E"] = 40;
			Post.macintoshStandardOrderGlyphIds["F"] = 41;
			Post.macintoshStandardOrderGlyphIds["G"] = 42;
			Post.macintoshStandardOrderGlyphIds["H"] = 43;
			Post.macintoshStandardOrderGlyphIds["I"] = 44;
			Post.macintoshStandardOrderGlyphIds["J"] = 45;
			Post.macintoshStandardOrderGlyphIds["K"] = 46;
			Post.macintoshStandardOrderGlyphIds["L"] = 47;
			Post.macintoshStandardOrderGlyphIds["M"] = 48;
			Post.macintoshStandardOrderGlyphIds["N"] = 49;
			Post.macintoshStandardOrderGlyphIds["O"] = 50;
			Post.macintoshStandardOrderGlyphIds["P"] = 51;
			Post.macintoshStandardOrderGlyphIds["Q"] = 52;
			Post.macintoshStandardOrderGlyphIds["R"] = 53;
			Post.macintoshStandardOrderGlyphIds["S"] = 54;
			Post.macintoshStandardOrderGlyphIds["T"] = 55;
			Post.macintoshStandardOrderGlyphIds["U"] = 56;
			Post.macintoshStandardOrderGlyphIds["V"] = 57;
			Post.macintoshStandardOrderGlyphIds["W"] = 58;
			Post.macintoshStandardOrderGlyphIds["X"] = 59;
			Post.macintoshStandardOrderGlyphIds["Y"] = 60;
			Post.macintoshStandardOrderGlyphIds["Z"] = 61;
			Post.macintoshStandardOrderGlyphIds["bracketleft"] = 62;
			Post.macintoshStandardOrderGlyphIds["backslash"] = 63;
			Post.macintoshStandardOrderGlyphIds["bracketright"] = 64;
			Post.macintoshStandardOrderGlyphIds["asciicircum"] = 65;
			Post.macintoshStandardOrderGlyphIds["underscore"] = 66;
			Post.macintoshStandardOrderGlyphIds["grave"] = 67;
			Post.macintoshStandardOrderGlyphIds["a"] = 68;
			Post.macintoshStandardOrderGlyphIds["b"] = 69;
			Post.macintoshStandardOrderGlyphIds["c"] = 70;
			Post.macintoshStandardOrderGlyphIds["d"] = 71;
			Post.macintoshStandardOrderGlyphIds["e"] = 72;
			Post.macintoshStandardOrderGlyphIds["f"] = 73;
			Post.macintoshStandardOrderGlyphIds["g"] = 74;
			Post.macintoshStandardOrderGlyphIds["h"] = 75;
			Post.macintoshStandardOrderGlyphIds["i"] = 76;
			Post.macintoshStandardOrderGlyphIds["j"] = 77;
			Post.macintoshStandardOrderGlyphIds["k"] = 78;
			Post.macintoshStandardOrderGlyphIds["l"] = 79;
			Post.macintoshStandardOrderGlyphIds["m"] = 80;
			Post.macintoshStandardOrderGlyphIds["n"] = 81;
			Post.macintoshStandardOrderGlyphIds["o"] = 82;
			Post.macintoshStandardOrderGlyphIds["p"] = 83;
			Post.macintoshStandardOrderGlyphIds["q"] = 84;
			Post.macintoshStandardOrderGlyphIds["r"] = 85;
			Post.macintoshStandardOrderGlyphIds["s"] = 86;
			Post.macintoshStandardOrderGlyphIds["t"] = 87;
			Post.macintoshStandardOrderGlyphIds["u"] = 88;
			Post.macintoshStandardOrderGlyphIds["v"] = 89;
			Post.macintoshStandardOrderGlyphIds["w"] = 90;
			Post.macintoshStandardOrderGlyphIds["x"] = 91;
			Post.macintoshStandardOrderGlyphIds["y"] = 92;
			Post.macintoshStandardOrderGlyphIds["z"] = 93;
			Post.macintoshStandardOrderGlyphIds["braceleft"] = 94;
			Post.macintoshStandardOrderGlyphIds["bar"] = 95;
			Post.macintoshStandardOrderGlyphIds["braceright"] = 96;
			Post.macintoshStandardOrderGlyphIds["asciitilde"] = 97;
			Post.macintoshStandardOrderGlyphIds["Adieresis"] = 98;
			Post.macintoshStandardOrderGlyphIds["Aring"] = 99;
			Post.macintoshStandardOrderGlyphIds["Ccedilla"] = 100;
			Post.macintoshStandardOrderGlyphIds["Eacute"] = 101;
			Post.macintoshStandardOrderGlyphIds["Ntilde"] = 102;
			Post.macintoshStandardOrderGlyphIds["Odieresis"] = 103;
			Post.macintoshStandardOrderGlyphIds["Udieresis"] = 104;
			Post.macintoshStandardOrderGlyphIds["aacute"] = 105;
			Post.macintoshStandardOrderGlyphIds["agrave"] = 106;
			Post.macintoshStandardOrderGlyphIds["acircumflex"] = 107;
			Post.macintoshStandardOrderGlyphIds["adieresis"] = 108;
			Post.macintoshStandardOrderGlyphIds["atilde"] = 109;
			Post.macintoshStandardOrderGlyphIds["aring"] = 110;
			Post.macintoshStandardOrderGlyphIds["ccedilla"] = 111;
			Post.macintoshStandardOrderGlyphIds["eacute"] = 112;
			Post.macintoshStandardOrderGlyphIds["egrave"] = 113;
			Post.macintoshStandardOrderGlyphIds["ecircumflex"] = 114;
			Post.macintoshStandardOrderGlyphIds["edieresis"] = 115;
			Post.macintoshStandardOrderGlyphIds["iacute"] = 116;
			Post.macintoshStandardOrderGlyphIds["igrave"] = 117;
			Post.macintoshStandardOrderGlyphIds["icircumflex"] = 118;
			Post.macintoshStandardOrderGlyphIds["idieresis"] = 119;
			Post.macintoshStandardOrderGlyphIds["ntilde"] = 120;
			Post.macintoshStandardOrderGlyphIds["oacute"] = 121;
			Post.macintoshStandardOrderGlyphIds["ograve"] = 122;
			Post.macintoshStandardOrderGlyphIds["ocircumflex"] = 123;
			Post.macintoshStandardOrderGlyphIds["odieresis"] = 124;
			Post.macintoshStandardOrderGlyphIds["otilde"] = 125;
			Post.macintoshStandardOrderGlyphIds["uacute"] = 126;
			Post.macintoshStandardOrderGlyphIds["ugrave"] = 127;
			Post.macintoshStandardOrderGlyphIds["ucircumflex"] = 128;
			Post.macintoshStandardOrderGlyphIds["udieresis"] = 129;
			Post.macintoshStandardOrderGlyphIds["dagger"] = 130;
			Post.macintoshStandardOrderGlyphIds["degree"] = 131;
			Post.macintoshStandardOrderGlyphIds["cent"] = 132;
			Post.macintoshStandardOrderGlyphIds["sterling"] = 133;
			Post.macintoshStandardOrderGlyphIds["section"] = 134;
			Post.macintoshStandardOrderGlyphIds["bullet"] = 135;
			Post.macintoshStandardOrderGlyphIds["paragraph"] = 136;
			Post.macintoshStandardOrderGlyphIds["germandbls"] = 137;
			Post.macintoshStandardOrderGlyphIds["registered"] = 138;
			Post.macintoshStandardOrderGlyphIds["copyright"] = 139;
			Post.macintoshStandardOrderGlyphIds["trademark"] = 140;
			Post.macintoshStandardOrderGlyphIds["acute"] = 141;
			Post.macintoshStandardOrderGlyphIds["dieresis"] = 142;
			Post.macintoshStandardOrderGlyphIds["notequal"] = 143;
			Post.macintoshStandardOrderGlyphIds["AE"] = 144;
			Post.macintoshStandardOrderGlyphIds["Oslash"] = 145;
			Post.macintoshStandardOrderGlyphIds["infinity"] = 146;
			Post.macintoshStandardOrderGlyphIds["plusminus"] = 147;
			Post.macintoshStandardOrderGlyphIds["lessequal"] = 148;
			Post.macintoshStandardOrderGlyphIds["greaterequal"] = 149;
			Post.macintoshStandardOrderGlyphIds["yen"] = 150;
			Post.macintoshStandardOrderGlyphIds["mu"] = 151;
			Post.macintoshStandardOrderGlyphIds["partialdiff"] = 152;
			Post.macintoshStandardOrderGlyphIds["summation"] = 153;
			Post.macintoshStandardOrderGlyphIds["product"] = 154;
			Post.macintoshStandardOrderGlyphIds["pi"] = 155;
			Post.macintoshStandardOrderGlyphIds["integral"] = 156;
			Post.macintoshStandardOrderGlyphIds["ordfeminine"] = 157;
			Post.macintoshStandardOrderGlyphIds["ordmasculine"] = 158;
			Post.macintoshStandardOrderGlyphIds["Omega"] = 159;
			Post.macintoshStandardOrderGlyphIds["ae"] = 160;
			Post.macintoshStandardOrderGlyphIds["oslash"] = 161;
			Post.macintoshStandardOrderGlyphIds["questiondown"] = 162;
			Post.macintoshStandardOrderGlyphIds["exclamdown"] = 163;
			Post.macintoshStandardOrderGlyphIds["logicalnot"] = 164;
			Post.macintoshStandardOrderGlyphIds["radical"] = 165;
			Post.macintoshStandardOrderGlyphIds["florin"] = 166;
			Post.macintoshStandardOrderGlyphIds["approxequal"] = 167;
			Post.macintoshStandardOrderGlyphIds["Delta"] = 168;
			Post.macintoshStandardOrderGlyphIds["guillemotleft"] = 169;
			Post.macintoshStandardOrderGlyphIds["guillemotright"] = 170;
			Post.macintoshStandardOrderGlyphIds["ellipsis"] = 171;
			Post.macintoshStandardOrderGlyphIds["nonbreakingspace"] = 172;
			Post.macintoshStandardOrderGlyphIds["Agrave"] = 173;
			Post.macintoshStandardOrderGlyphIds["Atilde"] = 174;
			Post.macintoshStandardOrderGlyphIds["Otilde"] = 175;
			Post.macintoshStandardOrderGlyphIds["OE"] = 176;
			Post.macintoshStandardOrderGlyphIds["oe"] = 177;
			Post.macintoshStandardOrderGlyphIds["endash"] = 178;
			Post.macintoshStandardOrderGlyphIds["emdash"] = 179;
			Post.macintoshStandardOrderGlyphIds["quotedblleft"] = 180;
			Post.macintoshStandardOrderGlyphIds["quotedblright"] = 181;
			Post.macintoshStandardOrderGlyphIds["quoteleft"] = 182;
			Post.macintoshStandardOrderGlyphIds["quoteright"] = 183;
			Post.macintoshStandardOrderGlyphIds["divide"] = 184;
			Post.macintoshStandardOrderGlyphIds["lozenge"] = 185;
			Post.macintoshStandardOrderGlyphIds["ydieresis"] = 186;
			Post.macintoshStandardOrderGlyphIds["Ydieresis"] = 187;
			Post.macintoshStandardOrderGlyphIds["fraction"] = 188;
			Post.macintoshStandardOrderGlyphIds["currency"] = 189;
			Post.macintoshStandardOrderGlyphIds["guilsinglleft"] = 190;
			Post.macintoshStandardOrderGlyphIds["guilsinglright"] = 191;
			Post.macintoshStandardOrderGlyphIds["fi"] = 192;
			Post.macintoshStandardOrderGlyphIds["fl"] = 193;
			Post.macintoshStandardOrderGlyphIds["daggerdbl"] = 194;
			Post.macintoshStandardOrderGlyphIds["periodcentered"] = 195;
			Post.macintoshStandardOrderGlyphIds["quotesinglbase"] = 196;
			Post.macintoshStandardOrderGlyphIds["quotedblbase"] = 197;
			Post.macintoshStandardOrderGlyphIds["perthousand"] = 198;
			Post.macintoshStandardOrderGlyphIds["Acircumflex"] = 199;
			Post.macintoshStandardOrderGlyphIds["Ecircumflex"] = 200;
			Post.macintoshStandardOrderGlyphIds["Aacute"] = 201;
			Post.macintoshStandardOrderGlyphIds["Edieresis"] = 202;
			Post.macintoshStandardOrderGlyphIds["Egrave"] = 203;
			Post.macintoshStandardOrderGlyphIds["Iacute"] = 204;
			Post.macintoshStandardOrderGlyphIds["Icircumflex"] = 205;
			Post.macintoshStandardOrderGlyphIds["Idieresis"] = 206;
			Post.macintoshStandardOrderGlyphIds["Igrave"] = 207;
			Post.macintoshStandardOrderGlyphIds["Oacute"] = 208;
			Post.macintoshStandardOrderGlyphIds["Ocircumflex"] = 209;
			Post.macintoshStandardOrderGlyphIds["apple"] = 210;
			Post.macintoshStandardOrderGlyphIds["Ograve"] = 211;
			Post.macintoshStandardOrderGlyphIds["Uacute"] = 212;
			Post.macintoshStandardOrderGlyphIds["Ucircumflex"] = 213;
			Post.macintoshStandardOrderGlyphIds["Ugrave"] = 214;
			Post.macintoshStandardOrderGlyphIds["dotlessi"] = 215;
			Post.macintoshStandardOrderGlyphIds["circumflex"] = 216;
			Post.macintoshStandardOrderGlyphIds["tilde"] = 217;
			Post.macintoshStandardOrderGlyphIds["macron"] = 218;
			Post.macintoshStandardOrderGlyphIds["breve"] = 219;
			Post.macintoshStandardOrderGlyphIds["dotaccent"] = 220;
			Post.macintoshStandardOrderGlyphIds["ring"] = 221;
			Post.macintoshStandardOrderGlyphIds["cedilla"] = 222;
			Post.macintoshStandardOrderGlyphIds["hungarumlaut"] = 223;
			Post.macintoshStandardOrderGlyphIds["ogonek"] = 224;
			Post.macintoshStandardOrderGlyphIds["caron"] = 225;
			Post.macintoshStandardOrderGlyphIds["Lslash"] = 226;
			Post.macintoshStandardOrderGlyphIds["lslash"] = 227;
			Post.macintoshStandardOrderGlyphIds["Scaron"] = 228;
			Post.macintoshStandardOrderGlyphIds["scaron"] = 229;
			Post.macintoshStandardOrderGlyphIds["Zcaron"] = 230;
			Post.macintoshStandardOrderGlyphIds["zcaron"] = 231;
			Post.macintoshStandardOrderGlyphIds["brokenbar"] = 232;
			Post.macintoshStandardOrderGlyphIds["Eth"] = 233;
			Post.macintoshStandardOrderGlyphIds["eth"] = 234;
			Post.macintoshStandardOrderGlyphIds["Yacute"] = 235;
			Post.macintoshStandardOrderGlyphIds["yacute"] = 236;
			Post.macintoshStandardOrderGlyphIds["Thorn"] = 237;
			Post.macintoshStandardOrderGlyphIds["thorn"] = 238;
			Post.macintoshStandardOrderGlyphIds["minus"] = 239;
			Post.macintoshStandardOrderGlyphIds["multiply"] = 240;
			Post.macintoshStandardOrderGlyphIds["onesuperior"] = 241;
			Post.macintoshStandardOrderGlyphIds["twosuperior"] = 242;
			Post.macintoshStandardOrderGlyphIds["threesuperior"] = 243;
			Post.macintoshStandardOrderGlyphIds["onehalf"] = 244;
			Post.macintoshStandardOrderGlyphIds["onequarter"] = 245;
			Post.macintoshStandardOrderGlyphIds["threequarters"] = 246;
			Post.macintoshStandardOrderGlyphIds["franc"] = 247;
			Post.macintoshStandardOrderGlyphIds["Gbreve"] = 248;
			Post.macintoshStandardOrderGlyphIds["gbreve"] = 249;
			Post.macintoshStandardOrderGlyphIds["Idotaccent"] = 250;
			Post.macintoshStandardOrderGlyphIds["Scedilla"] = 251;
			Post.macintoshStandardOrderGlyphIds["scedilla"] = 252;
			Post.macintoshStandardOrderGlyphIds["Cacute"] = 253;
			Post.macintoshStandardOrderGlyphIds["cacute"] = 254;
			Post.macintoshStandardOrderGlyphIds["Ccaron"] = 255;
			Post.macintoshStandardOrderGlyphIds["ccaron"] = 256;
			Post.macintoshStandardOrderGlyphIds["dcroat"] = 257;
			Post.macintoshStandardOrderNames = new string[258];
			Post.macintoshStandardOrderNames[0] = ".notdef";
			Post.macintoshStandardOrderNames[1] = ".null";
			Post.macintoshStandardOrderNames[2] = "nonmarkingreturn";
			Post.macintoshStandardOrderNames[3] = "space";
			Post.macintoshStandardOrderNames[4] = "exclam";
			Post.macintoshStandardOrderNames[5] = "quotedbl";
			Post.macintoshStandardOrderNames[6] = "numbersign";
			Post.macintoshStandardOrderNames[7] = "dollar";
			Post.macintoshStandardOrderNames[8] = "percent";
			Post.macintoshStandardOrderNames[9] = "ampersand";
			Post.macintoshStandardOrderNames[10] = "quotesingle";
			Post.macintoshStandardOrderNames[11] = "parenleft";
			Post.macintoshStandardOrderNames[12] = "parenright";
			Post.macintoshStandardOrderNames[13] = "asterisk";
			Post.macintoshStandardOrderNames[14] = "plus";
			Post.macintoshStandardOrderNames[15] = "comma";
			Post.macintoshStandardOrderNames[16] = "hyphen";
			Post.macintoshStandardOrderNames[17] = "period";
			Post.macintoshStandardOrderNames[18] = "slash";
			Post.macintoshStandardOrderNames[19] = "zero";
			Post.macintoshStandardOrderNames[20] = "one";
			Post.macintoshStandardOrderNames[21] = "two";
			Post.macintoshStandardOrderNames[22] = "three";
			Post.macintoshStandardOrderNames[23] = "four";
			Post.macintoshStandardOrderNames[24] = "five";
			Post.macintoshStandardOrderNames[25] = "six";
			Post.macintoshStandardOrderNames[26] = "seven";
			Post.macintoshStandardOrderNames[27] = "eight";
			Post.macintoshStandardOrderNames[28] = "nine";
			Post.macintoshStandardOrderNames[29] = "colon";
			Post.macintoshStandardOrderNames[30] = "semicolon";
			Post.macintoshStandardOrderNames[31] = "less";
			Post.macintoshStandardOrderNames[32] = "equal";
			Post.macintoshStandardOrderNames[33] = "greater";
			Post.macintoshStandardOrderNames[34] = "question";
			Post.macintoshStandardOrderNames[35] = "at";
			Post.macintoshStandardOrderNames[36] = "A";
			Post.macintoshStandardOrderNames[37] = "B";
			Post.macintoshStandardOrderNames[38] = "C";
			Post.macintoshStandardOrderNames[39] = "D";
			Post.macintoshStandardOrderNames[40] = "E";
			Post.macintoshStandardOrderNames[41] = "F";
			Post.macintoshStandardOrderNames[42] = "G";
			Post.macintoshStandardOrderNames[43] = "H";
			Post.macintoshStandardOrderNames[44] = "I";
			Post.macintoshStandardOrderNames[45] = "J";
			Post.macintoshStandardOrderNames[46] = "K";
			Post.macintoshStandardOrderNames[47] = "L";
			Post.macintoshStandardOrderNames[48] = "M";
			Post.macintoshStandardOrderNames[49] = "N";
			Post.macintoshStandardOrderNames[50] = "O";
			Post.macintoshStandardOrderNames[51] = "P";
			Post.macintoshStandardOrderNames[52] = "Q";
			Post.macintoshStandardOrderNames[53] = "R";
			Post.macintoshStandardOrderNames[54] = "S";
			Post.macintoshStandardOrderNames[55] = "T";
			Post.macintoshStandardOrderNames[56] = "U";
			Post.macintoshStandardOrderNames[57] = "V";
			Post.macintoshStandardOrderNames[58] = "W";
			Post.macintoshStandardOrderNames[59] = "X";
			Post.macintoshStandardOrderNames[60] = "Y";
			Post.macintoshStandardOrderNames[61] = "Z";
			Post.macintoshStandardOrderNames[62] = "bracketleft";
			Post.macintoshStandardOrderNames[63] = "backslash";
			Post.macintoshStandardOrderNames[64] = "bracketright";
			Post.macintoshStandardOrderNames[65] = "asciicircum";
			Post.macintoshStandardOrderNames[66] = "underscore";
			Post.macintoshStandardOrderNames[67] = "grave";
			Post.macintoshStandardOrderNames[68] = "a";
			Post.macintoshStandardOrderNames[69] = "b";
			Post.macintoshStandardOrderNames[70] = "c";
			Post.macintoshStandardOrderNames[71] = "d";
			Post.macintoshStandardOrderNames[72] = "e";
			Post.macintoshStandardOrderNames[73] = "f";
			Post.macintoshStandardOrderNames[74] = "g";
			Post.macintoshStandardOrderNames[75] = "h";
			Post.macintoshStandardOrderNames[76] = "i";
			Post.macintoshStandardOrderNames[77] = "j";
			Post.macintoshStandardOrderNames[78] = "k";
			Post.macintoshStandardOrderNames[79] = "l";
			Post.macintoshStandardOrderNames[80] = "m";
			Post.macintoshStandardOrderNames[81] = "n";
			Post.macintoshStandardOrderNames[82] = "o";
			Post.macintoshStandardOrderNames[83] = "p";
			Post.macintoshStandardOrderNames[84] = "q";
			Post.macintoshStandardOrderNames[85] = "r";
			Post.macintoshStandardOrderNames[86] = "s";
			Post.macintoshStandardOrderNames[87] = "t";
			Post.macintoshStandardOrderNames[88] = "u";
			Post.macintoshStandardOrderNames[89] = "v";
			Post.macintoshStandardOrderNames[90] = "w";
			Post.macintoshStandardOrderNames[91] = "x";
			Post.macintoshStandardOrderNames[92] = "y";
			Post.macintoshStandardOrderNames[93] = "z";
			Post.macintoshStandardOrderNames[94] = "braceleft";
			Post.macintoshStandardOrderNames[95] = "bar";
			Post.macintoshStandardOrderNames[96] = "braceright";
			Post.macintoshStandardOrderNames[97] = "asciitilde";
			Post.macintoshStandardOrderNames[98] = "Adieresis";
			Post.macintoshStandardOrderNames[99] = "Aring";
			Post.macintoshStandardOrderNames[100] = "Ccedilla";
			Post.macintoshStandardOrderNames[101] = "Eacute";
			Post.macintoshStandardOrderNames[102] = "Ntilde";
			Post.macintoshStandardOrderNames[103] = "Odieresis";
			Post.macintoshStandardOrderNames[104] = "Udieresis";
			Post.macintoshStandardOrderNames[105] = "aacute";
			Post.macintoshStandardOrderNames[106] = "agrave";
			Post.macintoshStandardOrderNames[107] = "acircumflex";
			Post.macintoshStandardOrderNames[108] = "adieresis";
			Post.macintoshStandardOrderNames[109] = "atilde";
			Post.macintoshStandardOrderNames[110] = "aring";
			Post.macintoshStandardOrderNames[111] = "ccedilla";
			Post.macintoshStandardOrderNames[112] = "eacute";
			Post.macintoshStandardOrderNames[113] = "egrave";
			Post.macintoshStandardOrderNames[114] = "ecircumflex";
			Post.macintoshStandardOrderNames[115] = "edieresis";
			Post.macintoshStandardOrderNames[116] = "iacute";
			Post.macintoshStandardOrderNames[117] = "igrave";
			Post.macintoshStandardOrderNames[118] = "icircumflex";
			Post.macintoshStandardOrderNames[119] = "idieresis";
			Post.macintoshStandardOrderNames[120] = "ntilde";
			Post.macintoshStandardOrderNames[121] = "oacute";
			Post.macintoshStandardOrderNames[122] = "ograve";
			Post.macintoshStandardOrderNames[123] = "ocircumflex";
			Post.macintoshStandardOrderNames[124] = "odieresis";
			Post.macintoshStandardOrderNames[125] = "otilde";
			Post.macintoshStandardOrderNames[126] = "uacute";
			Post.macintoshStandardOrderNames[127] = "ugrave";
			Post.macintoshStandardOrderNames[128] = "ucircumflex";
			Post.macintoshStandardOrderNames[129] = "udieresis";
			Post.macintoshStandardOrderNames[130] = "dagger";
			Post.macintoshStandardOrderNames[131] = "degree";
			Post.macintoshStandardOrderNames[132] = "cent";
			Post.macintoshStandardOrderNames[133] = "sterling";
			Post.macintoshStandardOrderNames[134] = "section";
			Post.macintoshStandardOrderNames[135] = "bullet";
			Post.macintoshStandardOrderNames[136] = "paragraph";
			Post.macintoshStandardOrderNames[137] = "germandbls";
			Post.macintoshStandardOrderNames[138] = "registered";
			Post.macintoshStandardOrderNames[139] = "copyright";
			Post.macintoshStandardOrderNames[140] = "trademark";
			Post.macintoshStandardOrderNames[141] = "acute";
			Post.macintoshStandardOrderNames[142] = "dieresis";
			Post.macintoshStandardOrderNames[143] = "notequal";
			Post.macintoshStandardOrderNames[144] = "AE";
			Post.macintoshStandardOrderNames[145] = "Oslash";
			Post.macintoshStandardOrderNames[146] = "infinity";
			Post.macintoshStandardOrderNames[147] = "plusminus";
			Post.macintoshStandardOrderNames[148] = "lessequal";
			Post.macintoshStandardOrderNames[149] = "greaterequal";
			Post.macintoshStandardOrderNames[150] = "yen";
			Post.macintoshStandardOrderNames[151] = "mu";
			Post.macintoshStandardOrderNames[152] = "partialdiff";
			Post.macintoshStandardOrderNames[153] = "summation";
			Post.macintoshStandardOrderNames[154] = "product";
			Post.macintoshStandardOrderNames[155] = "pi";
			Post.macintoshStandardOrderNames[156] = "integral";
			Post.macintoshStandardOrderNames[157] = "ordfeminine";
			Post.macintoshStandardOrderNames[158] = "ordmasculine";
			Post.macintoshStandardOrderNames[159] = "Omega";
			Post.macintoshStandardOrderNames[160] = "ae";
			Post.macintoshStandardOrderNames[161] = "oslash";
			Post.macintoshStandardOrderNames[162] = "questiondown";
			Post.macintoshStandardOrderNames[163] = "exclamdown";
			Post.macintoshStandardOrderNames[164] = "logicalnot";
			Post.macintoshStandardOrderNames[165] = "radical";
			Post.macintoshStandardOrderNames[166] = "florin";
			Post.macintoshStandardOrderNames[167] = "approxequal";
			Post.macintoshStandardOrderNames[168] = "Delta";
			Post.macintoshStandardOrderNames[169] = "guillemotleft";
			Post.macintoshStandardOrderNames[170] = "guillemotright";
			Post.macintoshStandardOrderNames[171] = "ellipsis";
			Post.macintoshStandardOrderNames[172] = "nonbreakingspace";
			Post.macintoshStandardOrderNames[173] = "Agrave";
			Post.macintoshStandardOrderNames[174] = "Atilde";
			Post.macintoshStandardOrderNames[175] = "Otilde";
			Post.macintoshStandardOrderNames[176] = "OE";
			Post.macintoshStandardOrderNames[177] = "oe";
			Post.macintoshStandardOrderNames[178] = "endash";
			Post.macintoshStandardOrderNames[179] = "emdash";
			Post.macintoshStandardOrderNames[180] = "quotedblleft";
			Post.macintoshStandardOrderNames[181] = "quotedblright";
			Post.macintoshStandardOrderNames[182] = "quoteleft";
			Post.macintoshStandardOrderNames[183] = "quoteright";
			Post.macintoshStandardOrderNames[184] = "divide";
			Post.macintoshStandardOrderNames[185] = "lozenge";
			Post.macintoshStandardOrderNames[186] = "ydieresis";
			Post.macintoshStandardOrderNames[187] = "Ydieresis";
			Post.macintoshStandardOrderNames[188] = "fraction";
			Post.macintoshStandardOrderNames[189] = "currency";
			Post.macintoshStandardOrderNames[190] = "guilsinglleft";
			Post.macintoshStandardOrderNames[191] = "guilsinglright";
			Post.macintoshStandardOrderNames[192] = "fi";
			Post.macintoshStandardOrderNames[193] = "fl";
			Post.macintoshStandardOrderNames[194] = "daggerdbl";
			Post.macintoshStandardOrderNames[195] = "periodcentered";
			Post.macintoshStandardOrderNames[196] = "quotesinglbase";
			Post.macintoshStandardOrderNames[197] = "quotedblbase";
			Post.macintoshStandardOrderNames[198] = "perthousand";
			Post.macintoshStandardOrderNames[199] = "Acircumflex";
			Post.macintoshStandardOrderNames[200] = "Ecircumflex";
			Post.macintoshStandardOrderNames[201] = "Aacute";
			Post.macintoshStandardOrderNames[202] = "Edieresis";
			Post.macintoshStandardOrderNames[203] = "Egrave";
			Post.macintoshStandardOrderNames[204] = "Iacute";
			Post.macintoshStandardOrderNames[205] = "Icircumflex";
			Post.macintoshStandardOrderNames[206] = "Idieresis";
			Post.macintoshStandardOrderNames[207] = "Igrave";
			Post.macintoshStandardOrderNames[208] = "Oacute";
			Post.macintoshStandardOrderNames[209] = "Ocircumflex";
			Post.macintoshStandardOrderNames[210] = "apple";
			Post.macintoshStandardOrderNames[211] = "Ograve";
			Post.macintoshStandardOrderNames[212] = "Uacute";
			Post.macintoshStandardOrderNames[213] = "Ucircumflex";
			Post.macintoshStandardOrderNames[214] = "Ugrave";
			Post.macintoshStandardOrderNames[215] = "dotlessi";
			Post.macintoshStandardOrderNames[216] = "circumflex";
			Post.macintoshStandardOrderNames[217] = "tilde";
			Post.macintoshStandardOrderNames[218] = "macron";
			Post.macintoshStandardOrderNames[219] = "breve";
			Post.macintoshStandardOrderNames[220] = "dotaccent";
			Post.macintoshStandardOrderNames[221] = "ring";
			Post.macintoshStandardOrderNames[222] = "cedilla";
			Post.macintoshStandardOrderNames[223] = "hungarumlaut";
			Post.macintoshStandardOrderNames[224] = "ogonek";
			Post.macintoshStandardOrderNames[225] = "caron";
			Post.macintoshStandardOrderNames[226] = "Lslash";
			Post.macintoshStandardOrderNames[227] = "lslash";
			Post.macintoshStandardOrderNames[228] = "Scaron";
			Post.macintoshStandardOrderNames[229] = "scaron";
			Post.macintoshStandardOrderNames[230] = "Zcaron";
			Post.macintoshStandardOrderNames[231] = "zcaron";
			Post.macintoshStandardOrderNames[232] = "brokenbar";
			Post.macintoshStandardOrderNames[233] = "Eth";
			Post.macintoshStandardOrderNames[234] = "eth";
			Post.macintoshStandardOrderNames[235] = "Yacute";
			Post.macintoshStandardOrderNames[236] = "yacute";
			Post.macintoshStandardOrderNames[237] = "Thorn";
			Post.macintoshStandardOrderNames[238] = "thorn";
			Post.macintoshStandardOrderNames[239] = "minus";
			Post.macintoshStandardOrderNames[240] = "multiply";
			Post.macintoshStandardOrderNames[241] = "onesuperior";
			Post.macintoshStandardOrderNames[242] = "twosuperior";
			Post.macintoshStandardOrderNames[243] = "threesuperior";
			Post.macintoshStandardOrderNames[244] = "onehalf";
			Post.macintoshStandardOrderNames[245] = "onequarter";
			Post.macintoshStandardOrderNames[246] = "threequarters";
			Post.macintoshStandardOrderNames[247] = "franc";
			Post.macintoshStandardOrderNames[248] = "Gbreve";
			Post.macintoshStandardOrderNames[249] = "gbreve";
			Post.macintoshStandardOrderNames[250] = "Idotaccent";
			Post.macintoshStandardOrderNames[251] = "Scedilla";
			Post.macintoshStandardOrderNames[252] = "scedilla";
			Post.macintoshStandardOrderNames[253] = "Cacute";
			Post.macintoshStandardOrderNames[254] = "cacute";
			Post.macintoshStandardOrderNames[255] = "Ccaron";
			Post.macintoshStandardOrderNames[256] = "ccaron";
			Post.macintoshStandardOrderNames[257] = "dcroat";
		}

		protected static Dictionary<string, ushort> macintoshStandardOrderGlyphIds;

		protected static string[] macintoshStandardOrderNames;
	}
}
