using System;

namespace HtmlParserSharp.Core
{
	sealed class NamedCharacters
	{
		internal static readonly string[] NAMES = new string[]
		{
			"lig", "lig;", "P", "P;", "cute", "cute;", "reve;", "irc", "irc;", "y;",
			"r;", "rave", "rave;", "pha;", "acr;", "d;", "gon;", "pf;", "plyFunction;", "ing",
			"ing;", "cr;", "sign;", "ilde", "ilde;", "ml", "ml;", "ckslash;", "rv;", "rwed;",
			"y;", "cause;", "rnoullis;", "ta;", "r;", "pf;", "eve;", "cr;", "mpeq;", "cy;",
			"PY", "PY;", "cute;", "p;", "pitalDifferentialD;", "yleys;", "aron;", "edil", "edil;", "irc;",
			"onint;", "ot;", "dilla;", "nterDot;", "r;", "i;", "rcleDot;", "rcleMinus;", "rclePlus;", "rcleTimes;",
			"ockwiseContourIntegral;", "oseCurlyDoubleQuote;", "oseCurlyQuote;", "lon;", "lone;", "ngruent;", "nint;", "ntourIntegral;", "pf;", "product;",
			"unterClockwiseContourIntegral;", "oss;", "cr;", "p;", "pCap;", ";", "otrahd;", "cy;", "cy;", "cy;",
			"gger;", "rr;", "shv;", "aron;", "y;", "l;", "lta;", "r;", "acriticalAcute;", "acriticalDot;",
			"acriticalDoubleAcute;", "acriticalGrave;", "acriticalTilde;", "amond;", "fferentialD;", "pf;", "t;", "tDot;", "tEqual;", "ubleContourIntegral;",
			"ubleDot;", "ubleDownArrow;", "ubleLeftArrow;", "ubleLeftRightArrow;", "ubleLeftTee;", "ubleLongLeftArrow;", "ubleLongLeftRightArrow;", "ubleLongRightArrow;", "ubleRightArrow;", "ubleRightTee;",
			"ubleUpArrow;", "ubleUpDownArrow;", "ubleVerticalBar;", "wnArrow;", "wnArrowBar;", "wnArrowUpArrow;", "wnBreve;", "wnLeftRightVector;", "wnLeftTeeVector;", "wnLeftVector;",
			"wnLeftVectorBar;", "wnRightTeeVector;", "wnRightVector;", "wnRightVectorBar;", "wnTee;", "wnTeeArrow;", "wnarrow;", "cr;", "trok;", "G;",
			"H", "H;", "cute", "cute;", "aron;", "irc", "irc;", "y;", "ot;", "r;",
			"rave", "rave;", "ement;", "acr;", "ptySmallSquare;", "ptyVerySmallSquare;", "gon;", "pf;", "silon;", "ual;",
			"ualTilde;", "uilibrium;", "cr;", "im;", "a;", "ml", "ml;", "ists;", "ponentialE;", "y;",
			"r;", "lledSmallSquare;", "lledVerySmallSquare;", "pf;", "rAll;", "uriertrf;", "cr;", "cy;", "", ";",
			"mma;", "mmad;", "reve;", "edil;", "irc;", "y;", "ot;", "r;", ";", "pf;",
			"eaterEqual;", "eaterEqualLess;", "eaterFullEqual;", "eaterGreater;", "eaterLess;", "eaterSlantEqual;", "eaterTilde;", "cr;", ";", "RDcy;",
			"cek;", "t;", "irc;", "r;", "lbertSpace;", "pf;", "rizontalLine;", "cr;", "trok;", "mpDownHump;",
			"mpEqual;", "cy;", "lig;", "cy;", "cute", "cute;", "irc", "irc;", "y;", "ot;",
			"r;", "rave", "rave;", ";", "acr;", "aginaryI;", "plies;", "t;", "tegral;", "tersection;",
			"visibleComma;", "visibleTimes;", "gon;", "pf;", "ta;", "cr;", "ilde;", "kcy;", "ml", "ml;",
			"irc;", "y;", "r;", "pf;", "cr;", "ercy;", "kcy;", "cy;", "cy;", "ppa;",
			"edil;", "y;", "r;", "pf;", "cr;", "cy;", "", ";", "cute;", "mbda;",
			"ng;", "placetrf;", "rr;", "aron;", "edil;", "y;", "ftAngleBracket;", "ftArrow;", "ftArrowBar;", "ftArrowRightArrow;",
			"ftCeiling;", "ftDoubleBracket;", "ftDownTeeVector;", "ftDownVector;", "ftDownVectorBar;", "ftFloor;", "ftRightArrow;", "ftRightVector;", "ftTee;", "ftTeeArrow;",
			"ftTeeVector;", "ftTriangle;", "ftTriangleBar;", "ftTriangleEqual;", "ftUpDownVector;", "ftUpTeeVector;", "ftUpVector;", "ftUpVectorBar;", "ftVector;", "ftVectorBar;",
			"ftarrow;", "ftrightarrow;", "ssEqualGreater;", "ssFullEqual;", "ssGreater;", "ssLess;", "ssSlantEqual;", "ssTilde;", "r;", ";",
			"eftarrow;", "idot;", "ngLeftArrow;", "ngLeftRightArrow;", "ngRightArrow;", "ngleftarrow;", "ngleftrightarrow;", "ngrightarrow;", "pf;", "werLeftArrow;",
			"werRightArrow;", "cr;", "h;", "trok;", ";", "p;", "y;", "diumSpace;", "llintrf;", "r;",
			"nusPlus;", "pf;", "cr;", ";", "cy;", "cute;", "aron;", "edil;", "y;", "gativeMediumSpace;",
			"gativeThickSpace;", "gativeThinSpace;", "gativeVeryThinSpace;", "stedGreaterGreater;", "stedLessLess;", "wLine;", "r;", "Break;", "nBreakingSpace;", "pf;",
			"t;", "tCongruent;", "tCupCap;", "tDoubleVerticalBar;", "tElement;", "tEqual;", "tEqualTilde;", "tExists;", "tGreater;", "tGreaterEqual;",
			"tGreaterFullEqual;", "tGreaterGreater;", "tGreaterLess;", "tGreaterSlantEqual;", "tGreaterTilde;", "tHumpDownHump;", "tHumpEqual;", "tLeftTriangle;", "tLeftTriangleBar;", "tLeftTriangleEqual;",
			"tLess;", "tLessEqual;", "tLessGreater;", "tLessLess;", "tLessSlantEqual;", "tLessTilde;", "tNestedGreaterGreater;", "tNestedLessLess;", "tPrecedes;", "tPrecedesEqual;",
			"tPrecedesSlantEqual;", "tReverseElement;", "tRightTriangle;", "tRightTriangleBar;", "tRightTriangleEqual;", "tSquareSubset;", "tSquareSubsetEqual;", "tSquareSuperset;", "tSquareSupersetEqual;", "tSubset;",
			"tSubsetEqual;", "tSucceeds;", "tSucceedsEqual;", "tSucceedsSlantEqual;", "tSucceedsTilde;", "tSuperset;", "tSupersetEqual;", "tTilde;", "tTildeEqual;", "tTildeFullEqual;",
			"tTildeTilde;", "tVerticalBar;", "cr;", "ilde", "ilde;", ";", "lig;", "cute", "cute;", "irc",
			"irc;", "y;", "blac;", "r;", "rave", "rave;", "acr;", "ega;", "icron;", "pf;",
			"enCurlyDoubleQuote;", "enCurlyQuote;", ";", "cr;", "lash", "lash;", "ilde", "ilde;", "imes;", "ml",
			"ml;", "erBar;", "erBrace;", "erBracket;", "erParenthesis;", "rtialD;", "y;", "r;", "i;", ";",
			"usMinus;", "incareplane;", "pf;", ";", "ecedes;", "ecedesEqual;", "ecedesSlantEqual;", "ecedesTilde;", "ime;", "oduct;",
			"oportion;", "oportional;", "cr;", "i;", "OT", "OT;", "r;", "pf;", "cr;", "arr;",
			"G", "G;", "cute;", "ng;", "rr;", "rrtl;", "aron;", "edil;", "y;", ";",
			"verseElement;", "verseEquilibrium;", "verseUpEquilibrium;", "r;", "o;", "ghtAngleBracket;", "ghtArrow;", "ghtArrowBar;", "ghtArrowLeftArrow;", "ghtCeiling;",
			"ghtDoubleBracket;", "ghtDownTeeVector;", "ghtDownVector;", "ghtDownVectorBar;", "ghtFloor;", "ghtTee;", "ghtTeeArrow;", "ghtTeeVector;", "ghtTriangle;", "ghtTriangleBar;",
			"ghtTriangleEqual;", "ghtUpDownVector;", "ghtUpTeeVector;", "ghtUpVector;", "ghtUpVectorBar;", "ghtVector;", "ghtVectorBar;", "ghtarrow;", "pf;", "undImplies;",
			"ightarrow;", "cr;", "h;", "leDelayed;", "CHcy;", "cy;", "FTcy;", "cute;", ";", "aron;",
			"edil;", "irc;", "y;", "r;", "ortDownArrow;", "ortLeftArrow;", "ortRightArrow;", "ortUpArrow;", "gma;", "allCircle;",
			"pf;", "rt;", "uare;", "uareIntersection;", "uareSubset;", "uareSubsetEqual;", "uareSuperset;", "uareSupersetEqual;", "uareUnion;", "cr;",
			"ar;", "b;", "bset;", "bsetEqual;", "cceeds;", "cceedsEqual;", "cceedsSlantEqual;", "cceedsTilde;", "chThat;", "m;",
			"p;", "perset;", "persetEqual;", "pset;", "ORN", "ORN;", "ADE;", "Hcy;", "cy;", "b;",
			"u;", "aron;", "edil;", "y;", "r;", "erefore;", "eta;", "ickSpace;", "inSpace;", "lde;",
			"ldeEqual;", "ldeFullEqual;", "ldeTilde;", "pf;", "ipleDot;", "cr;", "trok;", "cute", "cute;", "rr;",
			"rrocir;", "rcy;", "reve;", "irc", "irc;", "y;", "blac;", "r;", "rave", "rave;",
			"acr;", "derBar;", "derBrace;", "derBracket;", "derParenthesis;", "ion;", "ionPlus;", "gon;", "pf;", "Arrow;",
			"ArrowBar;", "ArrowDownArrow;", "DownArrow;", "Equilibrium;", "Tee;", "TeeArrow;", "arrow;", "downarrow;", "perLeftArrow;", "perRightArrow;",
			"si;", "silon;", "ing;", "cr;", "ilde;", "ml", "ml;", "ash;", "ar;", "y;",
			"ash;", "ashl;", "e;", "rbar;", "rt;", "rticalBar;", "rticalLine;", "rticalSeparator;", "rticalTilde;", "ryThinSpace;",
			"r;", "pf;", "cr;", "dash;", "irc;", "dge;", "r;", "pf;", "cr;", "r;",
			";", "pf;", "cr;", "cy;", "cy;", "cy;", "cute", "cute;", "irc;", "y;",
			"r;", "pf;", "cr;", "ml;", "cy;", "cute;", "aron;", "y;", "ot;", "roWidthSpace;",
			"ta;", "r;", "pf;", "cr;", "cute", "cute;", "reve;", ";", "E;", "d;",
			"irc", "irc;", "ute", "ute;", "y;", "lig", "lig;", ";", "r;", "rave",
			"rave;", "efsym;", "eph;", "pha;", "acr;", "alg;", "p", "p;", "d;", "dand;",
			"dd;", "dslope;", "dv;", "g;", "ge;", "gle;", "gmsd;", "gmsdaa;", "gmsdab;", "gmsdac;",
			"gmsdad;", "gmsdae;", "gmsdaf;", "gmsdag;", "gmsdah;", "grt;", "grtvb;", "grtvbd;", "gsph;", "gst;",
			"gzarr;", "gon;", "pf;", ";", "E;", "acir;", "e;", "id;", "os;", "prox;",
			"proxeq;", "ing", "ing;", "cr;", "t;", "ymp;", "ympeq;", "ilde", "ilde;", "ml",
			"ml;", "conint;", "int;", "ot;", "ckcong;", "ckepsilon;", "ckprime;", "cksim;", "cksimeq;", "rvee;",
			"rwed;", "rwedge;", "rk;", "rktbrk;", "ong;", "y;", "quo;", "caus;", "cause;", "mptyv;",
			"psi;", "rnou;", "ta;", "th;", "tween;", "r;", "gcap;", "gcirc;", "gcup;", "godot;",
			"goplus;", "gotimes;", "gsqcup;", "gstar;", "gtriangledown;", "gtriangleup;", "guplus;", "gvee;", "gwedge;", "arow;",
			"acklozenge;", "acksquare;", "acktriangle;", "acktriangledown;", "acktriangleleft;", "acktriangleright;", "ank;", "k12;", "k14;", "k34;",
			"ock;", "e;", "equiv;", "ot;", "pf;", "t;", "ttom;", "wtie;", "xDL;", "xDR;",
			"xDl;", "xDr;", "xH;", "xHD;", "xHU;", "xHd;", "xHu;", "xUL;", "xUR;", "xUl;",
			"xUr;", "xV;", "xVH;", "xVL;", "xVR;", "xVh;", "xVl;", "xVr;", "xbox;", "xdL;",
			"xdR;", "xdl;", "xdr;", "xh;", "xhD;", "xhU;", "xhd;", "xhu;", "xminus;", "xplus;",
			"xtimes;", "xuL;", "xuR;", "xul;", "xur;", "xv;", "xvH;", "xvL;", "xvR;", "xvh;",
			"xvl;", "xvr;", "rime;", "eve;", "vbar", "vbar;", "cr;", "emi;", "im;", "ime;",
			"ol;", "olb;", "olhsub;", "ll;", "llet;", "mp;", "mpE;", "mpe;", "mpeq;", "cute;",
			"p;", "pand;", "pbrcup;", "pcap;", "pcup;", "pdot;", "ps;", "ret;", "ron;", "aps;",
			"aron;", "edil", "edil;", "irc;", "ups;", "upssm;", "ot;", "dil", "dil;", "mptyv;",
			"nt", "nt;", "nterdot;", "r;", "cy;", "eck;", "eckmark;", "i;", "r;", "rE;",
			"rc;", "rceq;", "rclearrowleft;", "rclearrowright;", "rcledR;", "rcledS;", "rcledast;", "rcledcirc;", "rcleddash;", "re;",
			"rfnint;", "rmid;", "rscir;", "ubs;", "ubsuit;", "lon;", "lone;", "loneq;", "mma;", "mmat;",
			"mp;", "mpfn;", "mplement;", "mplexes;", "ng;", "ngdot;", "nint;", "pf;", "prod;", "py",
			"py;", "pysr;", "arr;", "oss;", "cr;", "ub;", "ube;", "up;", "upe;", "dot;",
			"darrl;", "darrr;", "epr;", "esc;", "larr;", "larrp;", "p;", "pbrcap;", "pcap;", "pcup;",
			"pdot;", "por;", "ps;", "rarr;", "rarrm;", "rlyeqprec;", "rlyeqsucc;", "rlyvee;", "rlywedge;", "rren",
			"rren;", "rvearrowleft;", "rvearrowright;", "vee;", "wed;", "conint;", "int;", "lcty;", "rr;", "ar;",
			"gger;", "leth;", "rr;", "sh;", "shv;", "karow;", "lac;", "aron;", "y;", ";",
			"agger;", "arr;", "otseq;", "g", "g;", "lta;", "mptyv;", "isht;", "r;", "arl;",
			"arr;", "am;", "amond;", "amondsuit;", "ams;", "e;", "gamma;", "sin;", "v;", "vide",
			"vide;", "videontimes;", "vonx;", "cy;", "corn;", "crop;", "llar;", "pf;", "t;", "teq;",
			"teqdot;", "tminus;", "tplus;", "tsquare;", "ublebarwedge;", "wnarrow;", "wndownarrows;", "wnharpoonleft;", "wnharpoonright;", "bkarow;",
			"corn;", "crop;", "cr;", "cy;", "ol;", "trok;", "dot;", "ri;", "rif;", "arr;",
			"har;", "angle;", "cy;", "igrarr;", "Dot;", "ot;", "cute", "cute;", "ster;", "aron;",
			"ir;", "irc", "irc;", "olon;", "y;", "ot;", ";", "Dot;", "r;", ";",
			"rave", "rave;", "s;", "sdot;", ";", "inters;", "l;", "s;", "sdot;", "acr;",
			"pty;", "ptyset;", "ptyv;", "sp13;", "sp14;", "sp;", "g;", "sp;", "gon;", "pf;",
			"ar;", "arsl;", "lus;", "si;", "silon;", "siv;", "circ;", "colon;", "sim;", "slantgtr;",
			"slantless;", "uals;", "uest;", "uiv;", "uivDD;", "vparsl;", "Dot;", "arr;", "cr;", "dot;",
			"im;", "a;", "h", "h;", "ml", "ml;", "ro;", "cl;", "ist;", "pectation;",
			"ponentiale;", "llingdotseq;", "y;", "male;", "ilig;", "lig;", "llig;", "r;", "lig;", "lig;",
			"at;", "lig;", "tns;", "of;", "pf;", "rall;", "rk;", "rkv;", "artint;", "ac12",
			"ac12;", "ac13;", "ac14", "ac14;", "ac15;", "ac16;", "ac18;", "ac23;", "ac25;", "ac34",
			"ac34;", "ac35;", "ac38;", "ac45;", "ac56;", "ac58;", "ac78;", "asl;", "own;", "cr;",
			";", "l;", "cute;", "mma;", "mmad;", "p;", "reve;", "irc;", "y;", "ot;",
			";", "l;", "q;", "qq;", "qslant;", "s;", "scc;", "sdot;", "sdoto;", "sdotol;",
			"sl;", "sles;", "r;", ";", "g;", "mel;", "cy;", ";", "E;", "a;",
			"j;", "E;", "ap;", "approx;", "e;", "eq;", "eqq;", "sim;", "pf;", "ave;",
			"cr;", "im;", "ime;", "iml;", "", ";", "cc;", "cir;", "dot;", "lPar;",
			"quest;", "rapprox;", "rarr;", "rdot;", "reqless;", "reqqless;", "rless;", "rsim;", "ertneqq;", "nE;",
			"rr;", "irsp;", "lf;", "milt;", "rdcy;", "rr;", "rrcir;", "rrw;", "ar;", "irc;",
			"arts;", "artsuit;", "llip;", "rcon;", "r;", "searow;", "swarow;", "arr;", "mtht;", "okleftarrow;",
			"okrightarrow;", "pf;", "rbar;", "cr;", "lash;", "trok;", "bull;", "phen;", "cute", "cute;",
			";", "irc", "irc;", "y;", "cy;", "xcl", "xcl;", "f;", "r;", "rave",
			"rave;", ";", "iint;", "int;", "nfin;", "ota;", "lig;", "acr;", "age;", "agline;",
			"agpart;", "ath;", "of;", "ped;", ";", "care;", "fin;", "fintie;", "odot;", "t;",
			"tcal;", "tegers;", "tercal;", "tlarhk;", "tprod;", "cy;", "gon;", "pf;", "ta;", "rod;",
			"uest", "uest;", "cr;", "in;", "inE;", "indot;", "ins;", "insv;", "inv;", ";",
			"ilde;", "kcy;", "ml", "ml;", "irc;", "y;", "r;", "ath;", "pf;", "cr;",
			"ercy;", "kcy;", "ppa;", "ppav;", "edil;", "y;", "r;", "reen;", "cy;", "cy;",
			"pf;", "cr;", "arr;", "rr;", "tail;", "arr;", ";", "g;", "ar;", "cute;",
			"emptyv;", "gran;", "mbda;", "ng;", "ngd;", "ngle;", "p;", "quo", "quo;", "rr;",
			"rrb;", "rrbfs;", "rrfs;", "rrhk;", "rrlp;", "rrpl;", "rrsim;", "rrtl;", "t;", "tail;",
			"te;", "tes;", "arr;", "brk;", "race;", "rack;", "rke;", "rksld;", "rkslu;", "aron;",
			"edil;", "eil;", "ub;", "y;", "ca;", "quo;", "quor;", "rdhar;", "rushar;", "sh;",
			";", "ftarrow;", "ftarrowtail;", "ftharpoondown;", "ftharpoonup;", "ftleftarrows;", "ftrightarrow;", "ftrightarrows;", "ftrightharpoons;", "ftrightsquigarrow;",
			"ftthreetimes;", "g;", "q;", "qq;", "qslant;", "s;", "scc;", "sdot;", "sdoto;", "sdotor;",
			"sg;", "sges;", "ssapprox;", "ssdot;", "sseqgtr;", "sseqqgtr;", "ssgtr;", "sssim;", "isht;", "loor;",
			"r;", ";", "E;", "ard;", "aru;", "arul;", "blk;", "cy;", ";", "arr;",
			"corner;", "hard;", "tri;", "idot;", "oust;", "oustache;", "E;", "ap;", "approx;", "e;",
			"eq;", "eqq;", "sim;", "ang;", "arr;", "brk;", "ngleftarrow;", "ngleftrightarrow;", "ngmapsto;", "ngrightarrow;",
			"oparrowleft;", "oparrowright;", "par;", "pf;", "plus;", "times;", "wast;", "wbar;", "z;", "zenge;",
			"zf;", "ar;", "arlt;", "arr;", "corner;", "har;", "hard;", "m;", "tri;", "aquo;",
			"cr;", "h;", "im;", "ime;", "img;", "qb;", "quo;", "quor;", "trok;", "",
			";", "cc;", "cir;", "dot;", "hree;", "imes;", "larr;", "quest;", "rPar;", "ri;",
			"rie;", "rif;", "rdshar;", "ruhar;", "ertneqq;", "nE;", "Dot;", "cr", "cr;", "le;",
			"lt;", "ltese;", "p;", "psto;", "pstodown;", "pstoleft;", "pstoup;", "rker;", "omma;", "y;",
			"ash;", "asuredangle;", "r;", "o;", "cro", "cro;", "d;", "dast;", "dcir;", "ddot",
			"ddot;", "nus;", "nusb;", "nusd;", "nusdu;", "cp;", "dr;", "plus;", "dels;", "pf;",
			";", "cr;", "tpos;", ";", "ltimap;", "map;", "g;", "t;", "tv;", "eftarrow;",
			"eftrightarrow;", "l;", "t;", "tv;", "ightarrow;", "Dash;", "dash;", "bla;", "cute;", "ng;",
			"p;", "pE;", "pid;", "pos;", "pprox;", "tur;", "tural;", "turals;", "sp", "sp;",
			"ump;", "umpe;", "ap;", "aron;", "edil;", "ong;", "ongdot;", "up;", "y;", "ash;",
			";", "Arr;", "arhk;", "arr;", "arrow;", "dot;", "quiv;", "sear;", "sim;", "xist;",
			"xists;", "r;", "E;", "e;", "eq;", "eqq;", "eqslant;", "es;", "sim;", "t;",
			"tr;", "Arr;", "arr;", "par;", ";", "s;", "sd;", "v;", "cy;", "Arr;",
			"E;", "arr;", "dr;", "e;", "eftarrow;", "eftrightarrow;", "eq;", "eqq;", "eqslant;", "es;",
			"ess;", "sim;", "t;", "tri;", "trie;", "id;", "pf;", "t", "t;", "tin;",
			"tinE;", "tindot;", "tinva;", "tinvb;", "tinvc;", "tni;", "tniva;", "tnivb;", "tnivc;", "ar;",
			"arallel;", "arsl;", "art;", "olint;", "r;", "rcue;", "re;", "rec;", "receq;", "Arr;",
			"arr;", "arrc;", "arrw;", "ightarrow;", "tri;", "trie;", "c;", "ccue;", "ce;", "cr;",
			"hortmid;", "hortparallel;", "im;", "ime;", "imeq;", "mid;", "par;", "qsube;", "qsupe;", "ub;",
			"ubE;", "ube;", "ubset;", "ubseteq;", "ubseteqq;", "ucc;", "ucceq;", "up;", "upE;", "upe;",
			"upset;", "upseteq;", "upseteqq;", "gl;", "ilde", "ilde;", "lg;", "riangleleft;", "rianglelefteq;", "riangleright;",
			"rianglerighteq;", ";", "m;", "mero;", "msp;", "Dash;", "Harr;", "ap;", "dash;", "ge;",
			"gt;", "infin;", "lArr;", "le;", "lt;", "ltrie;", "rArr;", "rtrie;", "sim;", "Arr;",
			"arhk;", "arr;", "arrow;", "near;", ";", "cute", "cute;", "st;", "ir;", "irc",
			"irc;", "y;", "ash;", "blac;", "iv;", "ot;", "sold;", "lig;", "cir;", "r;",
			"on;", "rave", "rave;", "t;", "bar;", "m;", "nt;", "arr;", "cir;", "cross;",
			"ine;", "t;", "acr;", "ega;", "icron;", "id;", "inus;", "pf;", "ar;", "erp;",
			"lus;", ";", "arr;", "d;", "der;", "derof;", "df", "df;", "dm", "dm;",
			"igof;", "or;", "slope;", "v;", "cr;", "lash", "lash;", "ol;", "ilde", "ilde;",
			"imes;", "imesas;", "ml", "ml;", "bar;", "r;", "ra", "ra;", "rallel;", "rsim;",
			"rsl;", "rt;", "y;", "rcnt;", "riod;", "rmil;", "rp;", "rtenk;", "r;", "i;",
			"iv;", "mmat;", "one;", ";", "tchfork;", "v;", "anck;", "anckh;", "ankv;", "us;",
			"usacir;", "usb;", "uscir;", "usdo;", "usdu;", "use;", "usmn", "usmn;", "ussim;", "ustwo;",
			";", "intint;", "pf;", "und", "und;", ";", "E;", "ap;", "cue;", "e;",
			"ec;", "ecapprox;", "eccurlyeq;", "eceq;", "ecnapprox;", "ecneqq;", "ecnsim;", "ecsim;", "ime;", "imes;",
			"nE;", "nap;", "nsim;", "od;", "ofalar;", "ofline;", "ofsurf;", "op;", "opto;", "sim;",
			"urel;", "cr;", "i;", "ncsp;", "r;", "nt;", "pf;", "rime;", "cr;", "aternions;",
			"atint;", "est;", "esteq;", "ot", "ot;", "arr;", "rr;", "tail;", "arr;", "ar;",
			"ce;", "cute;", "dic;", "emptyv;", "ng;", "ngd;", "nge;", "ngle;", "quo", "quo;",
			"rr;", "rrap;", "rrb;", "rrbfs;", "rrc;", "rrfs;", "rrhk;", "rrlp;", "rrpl;", "rrsim;",
			"rrtl;", "rrw;", "tail;", "tio;", "tionals;", "arr;", "brk;", "race;", "rack;", "rke;",
			"rksld;", "rkslu;", "aron;", "edil;", "eil;", "ub;", "y;", "ca;", "ldhar;", "quo;",
			"quor;", "sh;", "al;", "aline;", "alpart;", "als;", "ct;", "g", "g;", "isht;",
			"loor;", "r;", "ard;", "aru;", "arul;", "o;", "ov;", "ghtarrow;", "ghtarrowtail;", "ghtharpoondown;",
			"ghtharpoonup;", "ghtleftarrows;", "ghtleftharpoons;", "ghtrightarrows;", "ghtsquigarrow;", "ghtthreetimes;", "ng;", "singdotseq;", "arr;", "har;",
			"m;", "oust;", "oustache;", "mid;", "ang;", "arr;", "brk;", "par;", "pf;", "plus;",
			"times;", "ar;", "argt;", "polint;", "arr;", "aquo;", "cr;", "h;", "qb;", "quo;",
			"quor;", "hree;", "imes;", "ri;", "rie;", "rif;", "riltri;", "luhar;", ";", "cute;",
			"quo;", ";", "E;", "ap;", "aron;", "cue;", "e;", "edil;", "irc;", "nE;",
			"nap;", "nsim;", "polint;", "sim;", "y;", "ot;", "otb;", "ote;", "Arr;", "arhk;",
			"arr;", "arrow;", "ct", "ct;", "mi;", "swar;", "tminus;", "tmn;", "xt;", "r;",
			"rown;", "arp;", "chcy;", "cy;", "ortmid;", "ortparallel;", "y", "y;", "gma;", "gmaf;",
			"gmav;", "m;", "mdot;", "me;", "meq;", "mg;", "mgE;", "ml;", "mlE;", "mne;",
			"mplus;", "mrarr;", "arr;", "allsetminus;", "ashp;", "eparsl;", "id;", "ile;", "t;", "te;",
			"tes;", "ftcy;", "l;", "lb;", "lbar;", "pf;", "ades;", "adesuit;", "ar;", "cap;",
			"caps;", "cup;", "cups;", "sub;", "sube;", "subset;", "subseteq;", "sup;", "supe;", "supset;",
			"supseteq;", "u;", "uare;", "uarf;", "uf;", "arr;", "cr;", "etmn;", "mile;", "tarf;",
			"ar;", "arf;", "raightepsilon;", "raightphi;", "rns;", "b;", "bE;", "bdot;", "be;", "bedot;",
			"bmult;", "bnE;", "bne;", "bplus;", "brarr;", "bset;", "bseteq;", "bseteqq;", "bsetneq;", "bsetneqq;",
			"bsim;", "bsub;", "bsup;", "cc;", "ccapprox;", "cccurlyeq;", "cceq;", "ccnapprox;", "ccneqq;", "ccnsim;",
			"ccsim;", "m;", "ng;", "p1", "p1;", "p2", "p2;", "p3", "p3;", "p;",
			"pE;", "pdot;", "pdsub;", "pe;", "pedot;", "phsol;", "phsub;", "plarr;", "pmult;", "pnE;",
			"pne;", "pplus;", "pset;", "pseteq;", "pseteqq;", "psetneq;", "psetneqq;", "psim;", "psub;", "psup;",
			"Arr;", "arhk;", "arr;", "arrow;", "nwar;", "lig", "lig;", "rget;", "u;", "rk;",
			"aron;", "edil;", "y;", "ot;", "lrec;", "r;", "ere4;", "erefore;", "eta;", "etasym;",
			"etav;", "ickapprox;", "icksim;", "insp;", "kap;", "ksim;", "orn", "orn;", "lde;", "mes",
			"mes;", "mesb;", "mesbar;", "mesd;", "nt;", "ea;", "p;", "pbot;", "pcir;", "pf;",
			"pfork;", "sa;", "rime;", "ade;", "iangle;", "iangledown;", "iangleleft;", "ianglelefteq;", "iangleq;", "iangleright;",
			"ianglerighteq;", "idot;", "ie;", "iminus;", "iplus;", "isb;", "itime;", "pezium;", "cr;", "cy;",
			"hcy;", "trok;", "ixt;", "oheadleftarrow;", "oheadrightarrow;", "rr;", "ar;", "cute", "cute;", "rr;",
			"rcy;", "reve;", "irc", "irc;", "y;", "arr;", "blac;", "har;", "isht;", "r;",
			"rave", "rave;", "arl;", "arr;", "blk;", "corn;", "corner;", "crop;", "tri;", "acr;",
			"l", "l;", "gon;", "pf;", "arrow;", "downarrow;", "harpoonleft;", "harpoonright;", "lus;", "si;",
			"sih;", "silon;", "uparrows;", "corn;", "corner;", "crop;", "ing;", "tri;", "cr;", "dot;",
			"ilde;", "ri;", "rif;", "arr;", "ml", "ml;", "angle;", "rr;", "ar;", "arv;",
			"ash;", "ngrt;", "repsilon;", "rkappa;", "rnothing;", "rphi;", "rpi;", "rpropto;", "rr;", "rrho;",
			"rsigma;", "rsubsetneq;", "rsubsetneqq;", "rsupsetneq;", "rsupsetneqq;", "rtheta;", "rtriangleleft;", "rtriangleright;", "y;", "ash;",
			"e;", "ebar;", "eeq;", "llip;", "rbar;", "rt;", "r;", "tri;", "sub;", "sup;",
			"pf;", "rop;", "tri;", "cr;", "ubnE;", "ubne;", "upnE;", "upne;", "igzag;", "irc;",
			"dbar;", "dge;", "dgeq;", "ierp;", "r;", "pf;", ";", ";", "eath;", "cr;",
			"ap;", "irc;", "up;", "tri;", "r;", "Arr;", "arr;", ";", "Arr;", "arr;",
			"ap;", "is;", "dot;", "pf;", "plus;", "time;", "Arr;", "arr;", "cr;", "qcup;",
			"plus;", "tri;", "ee;", "edge;", "cute", "cute;", "cy;", "irc;", "y;", "n",
			"n;", "r;", "cy;", "pf;", "cr;", "cy;", "ml", "ml;", "cute;", "aron;",
			"y;", "ot;", "etrf;", "ta;", "r;", "cy;", "grarr;", "pf;", "cr;", "j;",
			"nj;"
		};

		internal static readonly char[][] VALUES = new char[][]
		{
			new char[] { 'Æ' },
			new char[] { 'Æ' },
			new char[] { '&' },
			new char[] { '&' },
			new char[] { 'Á' },
			new char[] { 'Á' },
			new char[] { 'Ă' },
			new char[] { 'Â' },
			new char[] { 'Â' },
			new char[] { 'А' },
			new char[] { '\ud835', '\udd04' },
			new char[] { 'À' },
			new char[] { 'À' },
			new char[] { 'Α' },
			new char[] { 'Ā' },
			new char[] { '⩓' },
			new char[] { 'Ą' },
			new char[] { '\ud835', '\udd38' },
			new char[] { '\u2061' },
			new char[] { 'Å' },
			new char[] { 'Å' },
			new char[] { '\ud835', '\udc9c' },
			new char[] { '≔' },
			new char[] { 'Ã' },
			new char[] { 'Ã' },
			new char[] { 'Ä' },
			new char[] { 'Ä' },
			new char[] { '∖' },
			new char[] { '⫧' },
			new char[] { '⌆' },
			new char[] { 'Б' },
			new char[] { '∵' },
			new char[] { 'ℬ' },
			new char[] { 'Β' },
			new char[] { '\ud835', '\udd05' },
			new char[] { '\ud835', '\udd39' },
			new char[] { '\u02d8' },
			new char[] { 'ℬ' },
			new char[] { '≎' },
			new char[] { 'Ч' },
			new char[] { '©' },
			new char[] { '©' },
			new char[] { 'Ć' },
			new char[] { '⋒' },
			new char[] { 'ⅅ' },
			new char[] { 'ℭ' },
			new char[] { 'Č' },
			new char[] { 'Ç' },
			new char[] { 'Ç' },
			new char[] { 'Ĉ' },
			new char[] { '∰' },
			new char[] { 'Ċ' },
			new char[] { '\u00b8' },
			new char[] { '·' },
			new char[] { 'ℭ' },
			new char[] { 'Χ' },
			new char[] { '⊙' },
			new char[] { '⊖' },
			new char[] { '⊕' },
			new char[] { '⊗' },
			new char[] { '∲' },
			new char[] { '”' },
			new char[] { '’' },
			new char[] { '∷' },
			new char[] { '⩴' },
			new char[] { '≡' },
			new char[] { '∯' },
			new char[] { '∮' },
			new char[] { 'ℂ' },
			new char[] { '∐' },
			new char[] { '∳' },
			new char[] { '⨯' },
			new char[] { '\ud835', '\udc9e' },
			new char[] { '⋓' },
			new char[] { '≍' },
			new char[] { 'ⅅ' },
			new char[] { '⤑' },
			new char[] { 'Ђ' },
			new char[] { 'Ѕ' },
			new char[] { 'Џ' },
			new char[] { '‡' },
			new char[] { '↡' },
			new char[] { '⫤' },
			new char[] { 'Ď' },
			new char[] { 'Д' },
			new char[] { '∇' },
			new char[] { 'Δ' },
			new char[] { '\ud835', '\udd07' },
			new char[] { '\u00b4' },
			new char[] { '\u02d9' },
			new char[] { '\u02dd' },
			new char[] { '`' },
			new char[] { '\u02dc' },
			new char[] { '⋄' },
			new char[] { 'ⅆ' },
			new char[] { '\ud835', '\udd3b' },
			new char[] { '\u00a8' },
			new char[] { '\u20dc' },
			new char[] { '≐' },
			new char[] { '∯' },
			new char[] { '\u00a8' },
			new char[] { '⇓' },
			new char[] { '⇐' },
			new char[] { '⇔' },
			new char[] { '⫤' },
			new char[] { '⟸' },
			new char[] { '⟺' },
			new char[] { '⟹' },
			new char[] { '⇒' },
			new char[] { '⊨' },
			new char[] { '⇑' },
			new char[] { '⇕' },
			new char[] { '∥' },
			new char[] { '↓' },
			new char[] { '⤓' },
			new char[] { '⇵' },
			new char[] { '\u0311' },
			new char[] { '⥐' },
			new char[] { '⥞' },
			new char[] { '↽' },
			new char[] { '⥖' },
			new char[] { '⥟' },
			new char[] { '⇁' },
			new char[] { '⥗' },
			new char[] { '⊤' },
			new char[] { '↧' },
			new char[] { '⇓' },
			new char[] { '\ud835', '\udc9f' },
			new char[] { 'Đ' },
			new char[] { 'Ŋ' },
			new char[] { 'Ð' },
			new char[] { 'Ð' },
			new char[] { 'É' },
			new char[] { 'É' },
			new char[] { 'Ě' },
			new char[] { 'Ê' },
			new char[] { 'Ê' },
			new char[] { 'Э' },
			new char[] { 'Ė' },
			new char[] { '\ud835', '\udd08' },
			new char[] { 'È' },
			new char[] { 'È' },
			new char[] { '∈' },
			new char[] { 'Ē' },
			new char[] { '◻' },
			new char[] { '▫' },
			new char[] { 'Ę' },
			new char[] { '\ud835', '\udd3c' },
			new char[] { 'Ε' },
			new char[] { '⩵' },
			new char[] { '≂' },
			new char[] { '⇌' },
			new char[] { 'ℰ' },
			new char[] { '⩳' },
			new char[] { 'Η' },
			new char[] { 'Ë' },
			new char[] { 'Ë' },
			new char[] { '∃' },
			new char[] { 'ⅇ' },
			new char[] { 'Ф' },
			new char[] { '\ud835', '\udd09' },
			new char[] { '◼' },
			new char[] { '▪' },
			new char[] { '\ud835', '\udd3d' },
			new char[] { '∀' },
			new char[] { 'ℱ' },
			new char[] { 'ℱ' },
			new char[] { 'Ѓ' },
			new char[] { '>' },
			new char[] { '>' },
			new char[] { 'Γ' },
			new char[] { 'Ϝ' },
			new char[] { 'Ğ' },
			new char[] { 'Ģ' },
			new char[] { 'Ĝ' },
			new char[] { 'Г' },
			new char[] { 'Ġ' },
			new char[] { '\ud835', '\udd0a' },
			new char[] { '⋙' },
			new char[] { '\ud835', '\udd3e' },
			new char[] { '≥' },
			new char[] { '⋛' },
			new char[] { '≧' },
			new char[] { '⪢' },
			new char[] { '≷' },
			new char[] { '⩾' },
			new char[] { '≳' },
			new char[] { '\ud835', '\udca2' },
			new char[] { '≫' },
			new char[] { 'Ъ' },
			new char[] { 'ˇ' },
			new char[] { '^' },
			new char[] { 'Ĥ' },
			new char[] { 'ℌ' },
			new char[] { 'ℋ' },
			new char[] { 'ℍ' },
			new char[] { '─' },
			new char[] { 'ℋ' },
			new char[] { 'Ħ' },
			new char[] { '≎' },
			new char[] { '≏' },
			new char[] { 'Е' },
			new char[] { 'Ĳ' },
			new char[] { 'Ё' },
			new char[] { 'Í' },
			new char[] { 'Í' },
			new char[] { 'Î' },
			new char[] { 'Î' },
			new char[] { 'И' },
			new char[] { 'İ' },
			new char[] { 'ℑ' },
			new char[] { 'Ì' },
			new char[] { 'Ì' },
			new char[] { 'ℑ' },
			new char[] { 'Ī' },
			new char[] { 'ⅈ' },
			new char[] { '⇒' },
			new char[] { '∬' },
			new char[] { '∫' },
			new char[] { '⋂' },
			new char[] { '\u2063' },
			new char[] { '\u2062' },
			new char[] { 'Į' },
			new char[] { '\ud835', '\udd40' },
			new char[] { 'Ι' },
			new char[] { 'ℐ' },
			new char[] { 'Ĩ' },
			new char[] { 'І' },
			new char[] { 'Ï' },
			new char[] { 'Ï' },
			new char[] { 'Ĵ' },
			new char[] { 'Й' },
			new char[] { '\ud835', '\udd0d' },
			new char[] { '\ud835', '\udd41' },
			new char[] { '\ud835', '\udca5' },
			new char[] { 'Ј' },
			new char[] { 'Є' },
			new char[] { 'Х' },
			new char[] { 'Ќ' },
			new char[] { 'Κ' },
			new char[] { 'Ķ' },
			new char[] { 'К' },
			new char[] { '\ud835', '\udd0e' },
			new char[] { '\ud835', '\udd42' },
			new char[] { '\ud835', '\udca6' },
			new char[] { 'Љ' },
			new char[] { '<' },
			new char[] { '<' },
			new char[] { 'Ĺ' },
			new char[] { 'Λ' },
			new char[] { '⟪' },
			new char[] { 'ℒ' },
			new char[] { '↞' },
			new char[] { 'Ľ' },
			new char[] { 'Ļ' },
			new char[] { 'Л' },
			new char[] { '⟨' },
			new char[] { '←' },
			new char[] { '⇤' },
			new char[] { '⇆' },
			new char[] { '⌈' },
			new char[] { '⟦' },
			new char[] { '⥡' },
			new char[] { '⇃' },
			new char[] { '⥙' },
			new char[] { '⌊' },
			new char[] { '↔' },
			new char[] { '⥎' },
			new char[] { '⊣' },
			new char[] { '↤' },
			new char[] { '⥚' },
			new char[] { '⊲' },
			new char[] { '⧏' },
			new char[] { '⊴' },
			new char[] { '⥑' },
			new char[] { '⥠' },
			new char[] { '↿' },
			new char[] { '⥘' },
			new char[] { '↼' },
			new char[] { '⥒' },
			new char[] { '⇐' },
			new char[] { '⇔' },
			new char[] { '⋚' },
			new char[] { '≦' },
			new char[] { '≶' },
			new char[] { '⪡' },
			new char[] { '⩽' },
			new char[] { '≲' },
			new char[] { '\ud835', '\udd0f' },
			new char[] { '⋘' },
			new char[] { '⇚' },
			new char[] { 'Ŀ' },
			new char[] { '⟵' },
			new char[] { '⟷' },
			new char[] { '⟶' },
			new char[] { '⟸' },
			new char[] { '⟺' },
			new char[] { '⟹' },
			new char[] { '\ud835', '\udd43' },
			new char[] { '↙' },
			new char[] { '↘' },
			new char[] { 'ℒ' },
			new char[] { '↰' },
			new char[] { 'Ł' },
			new char[] { '≪' },
			new char[] { '⤅' },
			new char[] { 'М' },
			new char[] { '\u205f' },
			new char[] { 'ℳ' },
			new char[] { '\ud835', '\udd10' },
			new char[] { '∓' },
			new char[] { '\ud835', '\udd44' },
			new char[] { 'ℳ' },
			new char[] { 'Μ' },
			new char[] { 'Њ' },
			new char[] { 'Ń' },
			new char[] { 'Ň' },
			new char[] { 'Ņ' },
			new char[] { 'Н' },
			new char[] { '\u200b' },
			new char[] { '\u200b' },
			new char[] { '\u200b' },
			new char[] { '\u200b' },
			new char[] { '≫' },
			new char[] { '≪' },
			new char[] { '\n' },
			new char[] { '\ud835', '\udd11' },
			new char[] { '\u2060' },
			new char[] { '\u00a0' },
			new char[] { 'ℕ' },
			new char[] { '⫬' },
			new char[] { '≢' },
			new char[] { '≭' },
			new char[] { '∦' },
			new char[] { '∉' },
			new char[] { '≠' },
			new char[] { '≂', '\u0338' },
			new char[] { '∄' },
			new char[] { '≯' },
			new char[] { '≱' },
			new char[] { '≧', '\u0338' },
			new char[] { '≫', '\u0338' },
			new char[] { '≹' },
			new char[] { '⩾', '\u0338' },
			new char[] { '≵' },
			new char[] { '≎', '\u0338' },
			new char[] { '≏', '\u0338' },
			new char[] { '⋪' },
			new char[] { '⧏', '\u0338' },
			new char[] { '⋬' },
			new char[] { '≮' },
			new char[] { '≰' },
			new char[] { '≸' },
			new char[] { '≪', '\u0338' },
			new char[] { '⩽', '\u0338' },
			new char[] { '≴' },
			new char[] { '⪢', '\u0338' },
			new char[] { '⪡', '\u0338' },
			new char[] { '⊀' },
			new char[] { '⪯', '\u0338' },
			new char[] { '⋠' },
			new char[] { '∌' },
			new char[] { '⋫' },
			new char[] { '⧐', '\u0338' },
			new char[] { '⋭' },
			new char[] { '⊏', '\u0338' },
			new char[] { '⋢' },
			new char[] { '⊐', '\u0338' },
			new char[] { '⋣' },
			new char[] { '⊂', '\u20d2' },
			new char[] { '⊈' },
			new char[] { '⊁' },
			new char[] { '⪰', '\u0338' },
			new char[] { '⋡' },
			new char[] { '≿', '\u0338' },
			new char[] { '⊃', '\u20d2' },
			new char[] { '⊉' },
			new char[] { '≁' },
			new char[] { '≄' },
			new char[] { '≇' },
			new char[] { '≉' },
			new char[] { '∤' },
			new char[] { '\ud835', '\udca9' },
			new char[] { 'Ñ' },
			new char[] { 'Ñ' },
			new char[] { 'Ν' },
			new char[] { 'Œ' },
			new char[] { 'Ó' },
			new char[] { 'Ó' },
			new char[] { 'Ô' },
			new char[] { 'Ô' },
			new char[] { 'О' },
			new char[] { 'Ő' },
			new char[] { '\ud835', '\udd12' },
			new char[] { 'Ò' },
			new char[] { 'Ò' },
			new char[] { 'Ō' },
			new char[] { 'Ω' },
			new char[] { 'Ο' },
			new char[] { '\ud835', '\udd46' },
			new char[] { '“' },
			new char[] { '‘' },
			new char[] { '⩔' },
			new char[] { '\ud835', '\udcaa' },
			new char[] { 'Ø' },
			new char[] { 'Ø' },
			new char[] { 'Õ' },
			new char[] { 'Õ' },
			new char[] { '⨷' },
			new char[] { 'Ö' },
			new char[] { 'Ö' },
			new char[] { '‾' },
			new char[] { '⏞' },
			new char[] { '⎴' },
			new char[] { '⏜' },
			new char[] { '∂' },
			new char[] { 'П' },
			new char[] { '\ud835', '\udd13' },
			new char[] { 'Φ' },
			new char[] { 'Π' },
			new char[] { '±' },
			new char[] { 'ℌ' },
			new char[] { 'ℙ' },
			new char[] { '⪻' },
			new char[] { '≺' },
			new char[] { '⪯' },
			new char[] { '≼' },
			new char[] { '≾' },
			new char[] { '″' },
			new char[] { '∏' },
			new char[] { '∷' },
			new char[] { '∝' },
			new char[] { '\ud835', '\udcab' },
			new char[] { 'Ψ' },
			new char[] { '"' },
			new char[] { '"' },
			new char[] { '\ud835', '\udd14' },
			new char[] { 'ℚ' },
			new char[] { '\ud835', '\udcac' },
			new char[] { '⤐' },
			new char[] { '®' },
			new char[] { '®' },
			new char[] { 'Ŕ' },
			new char[] { '⟫' },
			new char[] { '↠' },
			new char[] { '⤖' },
			new char[] { 'Ř' },
			new char[] { 'Ŗ' },
			new char[] { 'Р' },
			new char[] { 'ℜ' },
			new char[] { '∋' },
			new char[] { '⇋' },
			new char[] { '⥯' },
			new char[] { 'ℜ' },
			new char[] { 'Ρ' },
			new char[] { '⟩' },
			new char[] { '→' },
			new char[] { '⇥' },
			new char[] { '⇄' },
			new char[] { '⌉' },
			new char[] { '⟧' },
			new char[] { '⥝' },
			new char[] { '⇂' },
			new char[] { '⥕' },
			new char[] { '⌋' },
			new char[] { '⊢' },
			new char[] { '↦' },
			new char[] { '⥛' },
			new char[] { '⊳' },
			new char[] { '⧐' },
			new char[] { '⊵' },
			new char[] { '⥏' },
			new char[] { '⥜' },
			new char[] { '↾' },
			new char[] { '⥔' },
			new char[] { '⇀' },
			new char[] { '⥓' },
			new char[] { '⇒' },
			new char[] { 'ℝ' },
			new char[] { '⥰' },
			new char[] { '⇛' },
			new char[] { 'ℛ' },
			new char[] { '↱' },
			new char[] { '⧴' },
			new char[] { 'Щ' },
			new char[] { 'Ш' },
			new char[] { 'Ь' },
			new char[] { 'Ś' },
			new char[] { '⪼' },
			new char[] { 'Š' },
			new char[] { 'Ş' },
			new char[] { 'Ŝ' },
			new char[] { 'С' },
			new char[] { '\ud835', '\udd16' },
			new char[] { '↓' },
			new char[] { '←' },
			new char[] { '→' },
			new char[] { '↑' },
			new char[] { 'Σ' },
			new char[] { '∘' },
			new char[] { '\ud835', '\udd4a' },
			new char[] { '√' },
			new char[] { '□' },
			new char[] { '⊓' },
			new char[] { '⊏' },
			new char[] { '⊑' },
			new char[] { '⊐' },
			new char[] { '⊒' },
			new char[] { '⊔' },
			new char[] { '\ud835', '\udcae' },
			new char[] { '⋆' },
			new char[] { '⋐' },
			new char[] { '⋐' },
			new char[] { '⊆' },
			new char[] { '≻' },
			new char[] { '⪰' },
			new char[] { '≽' },
			new char[] { '≿' },
			new char[] { '∋' },
			new char[] { '∑' },
			new char[] { '⋑' },
			new char[] { '⊃' },
			new char[] { '⊇' },
			new char[] { '⋑' },
			new char[] { 'Þ' },
			new char[] { 'Þ' },
			new char[] { '™' },
			new char[] { 'Ћ' },
			new char[] { 'Ц' },
			new char[] { '\t' },
			new char[] { 'Τ' },
			new char[] { 'Ť' },
			new char[] { 'Ţ' },
			new char[] { 'Т' },
			new char[] { '\ud835', '\udd17' },
			new char[] { '∴' },
			new char[] { 'Θ' },
			new char[] { '\u205f', '\u200a' },
			new char[] { '\u2009' },
			new char[] { '∼' },
			new char[] { '≃' },
			new char[] { '≅' },
			new char[] { '≈' },
			new char[] { '\ud835', '\udd4b' },
			new char[] { '\u20db' },
			new char[] { '\ud835', '\udcaf' },
			new char[] { 'Ŧ' },
			new char[] { 'Ú' },
			new char[] { 'Ú' },
			new char[] { '↟' },
			new char[] { '⥉' },
			new char[] { 'Ў' },
			new char[] { 'Ŭ' },
			new char[] { 'Û' },
			new char[] { 'Û' },
			new char[] { 'У' },
			new char[] { 'Ű' },
			new char[] { '\ud835', '\udd18' },
			new char[] { 'Ù' },
			new char[] { 'Ù' },
			new char[] { 'Ū' },
			new char[] { '_' },
			new char[] { '⏟' },
			new char[] { '⎵' },
			new char[] { '⏝' },
			new char[] { '⋃' },
			new char[] { '⊎' },
			new char[] { 'Ų' },
			new char[] { '\ud835', '\udd4c' },
			new char[] { '↑' },
			new char[] { '⤒' },
			new char[] { '⇅' },
			new char[] { '↕' },
			new char[] { '⥮' },
			new char[] { '⊥' },
			new char[] { '↥' },
			new char[] { '⇑' },
			new char[] { '⇕' },
			new char[] { '↖' },
			new char[] { '↗' },
			new char[] { 'ϒ' },
			new char[] { 'Υ' },
			new char[] { 'Ů' },
			new char[] { '\ud835', '\udcb0' },
			new char[] { 'Ũ' },
			new char[] { 'Ü' },
			new char[] { 'Ü' },
			new char[] { '⊫' },
			new char[] { '⫫' },
			new char[] { 'В' },
			new char[] { '⊩' },
			new char[] { '⫦' },
			new char[] { '⋁' },
			new char[] { '‖' },
			new char[] { '‖' },
			new char[] { '∣' },
			new char[] { '|' },
			new char[] { '❘' },
			new char[] { '≀' },
			new char[] { '\u200a' },
			new char[] { '\ud835', '\udd19' },
			new char[] { '\ud835', '\udd4d' },
			new char[] { '\ud835', '\udcb1' },
			new char[] { '⊪' },
			new char[] { 'Ŵ' },
			new char[] { '⋀' },
			new char[] { '\ud835', '\udd1a' },
			new char[] { '\ud835', '\udd4e' },
			new char[] { '\ud835', '\udcb2' },
			new char[] { '\ud835', '\udd1b' },
			new char[] { 'Ξ' },
			new char[] { '\ud835', '\udd4f' },
			new char[] { '\ud835', '\udcb3' },
			new char[] { 'Я' },
			new char[] { 'Ї' },
			new char[] { 'Ю' },
			new char[] { 'Ý' },
			new char[] { 'Ý' },
			new char[] { 'Ŷ' },
			new char[] { 'Ы' },
			new char[] { '\ud835', '\udd1c' },
			new char[] { '\ud835', '\udd50' },
			new char[] { '\ud835', '\udcb4' },
			new char[] { 'Ÿ' },
			new char[] { 'Ж' },
			new char[] { 'Ź' },
			new char[] { 'Ž' },
			new char[] { 'З' },
			new char[] { 'Ż' },
			new char[] { '\u200b' },
			new char[] { 'Ζ' },
			new char[] { 'ℨ' },
			new char[] { 'ℤ' },
			new char[] { '\ud835', '\udcb5' },
			new char[] { 'á' },
			new char[] { 'á' },
			new char[] { 'ă' },
			new char[] { '∾' },
			new char[] { '∾', '\u0333' },
			new char[] { '∿' },
			new char[] { 'â' },
			new char[] { 'â' },
			new char[] { '\u00b4' },
			new char[] { '\u00b4' },
			new char[] { 'а' },
			new char[] { 'æ' },
			new char[] { 'æ' },
			new char[] { '\u2061' },
			new char[] { '\ud835', '\udd1e' },
			new char[] { 'à' },
			new char[] { 'à' },
			new char[] { 'ℵ' },
			new char[] { 'ℵ' },
			new char[] { 'α' },
			new char[] { 'ā' },
			new char[] { '⨿' },
			new char[] { '&' },
			new char[] { '&' },
			new char[] { '∧' },
			new char[] { '⩕' },
			new char[] { '⩜' },
			new char[] { '⩘' },
			new char[] { '⩚' },
			new char[] { '∠' },
			new char[] { '⦤' },
			new char[] { '∠' },
			new char[] { '∡' },
			new char[] { '⦨' },
			new char[] { '⦩' },
			new char[] { '⦪' },
			new char[] { '⦫' },
			new char[] { '⦬' },
			new char[] { '⦭' },
			new char[] { '⦮' },
			new char[] { '⦯' },
			new char[] { '∟' },
			new char[] { '⊾' },
			new char[] { '⦝' },
			new char[] { '∢' },
			new char[] { 'Å' },
			new char[] { '⍼' },
			new char[] { 'ą' },
			new char[] { '\ud835', '\udd52' },
			new char[] { '≈' },
			new char[] { '⩰' },
			new char[] { '⩯' },
			new char[] { '≊' },
			new char[] { '≋' },
			new char[] { '\'' },
			new char[] { '≈' },
			new char[] { '≊' },
			new char[] { 'å' },
			new char[] { 'å' },
			new char[] { '\ud835', '\udcb6' },
			new char[] { '*' },
			new char[] { '≈' },
			new char[] { '≍' },
			new char[] { 'ã' },
			new char[] { 'ã' },
			new char[] { 'ä' },
			new char[] { 'ä' },
			new char[] { '∳' },
			new char[] { '⨑' },
			new char[] { '⫭' },
			new char[] { '≌' },
			new char[] { '϶' },
			new char[] { '‵' },
			new char[] { '∽' },
			new char[] { '⋍' },
			new char[] { '⊽' },
			new char[] { '⌅' },
			new char[] { '⌅' },
			new char[] { '⎵' },
			new char[] { '⎶' },
			new char[] { '≌' },
			new char[] { 'б' },
			new char[] { '„' },
			new char[] { '∵' },
			new char[] { '∵' },
			new char[] { '⦰' },
			new char[] { '϶' },
			new char[] { 'ℬ' },
			new char[] { 'β' },
			new char[] { 'ℶ' },
			new char[] { '≬' },
			new char[] { '\ud835', '\udd1f' },
			new char[] { '⋂' },
			new char[] { '◯' },
			new char[] { '⋃' },
			new char[] { '⨀' },
			new char[] { '⨁' },
			new char[] { '⨂' },
			new char[] { '⨆' },
			new char[] { '★' },
			new char[] { '▽' },
			new char[] { '△' },
			new char[] { '⨄' },
			new char[] { '⋁' },
			new char[] { '⋀' },
			new char[] { '⤍' },
			new char[] { '⧫' },
			new char[] { '▪' },
			new char[] { '▴' },
			new char[] { '▾' },
			new char[] { '◂' },
			new char[] { '▸' },
			new char[] { '␣' },
			new char[] { '▒' },
			new char[] { '░' },
			new char[] { '▓' },
			new char[] { '█' },
			new char[] { '=', '\u20e5' },
			new char[] { '≡', '\u20e5' },
			new char[] { '⌐' },
			new char[] { '\ud835', '\udd53' },
			new char[] { '⊥' },
			new char[] { '⊥' },
			new char[] { '⋈' },
			new char[] { '╗' },
			new char[] { '╔' },
			new char[] { '╖' },
			new char[] { '╓' },
			new char[] { '═' },
			new char[] { '╦' },
			new char[] { '╩' },
			new char[] { '╤' },
			new char[] { '╧' },
			new char[] { '╝' },
			new char[] { '╚' },
			new char[] { '╜' },
			new char[] { '╙' },
			new char[] { '║' },
			new char[] { '╬' },
			new char[] { '╣' },
			new char[] { '╠' },
			new char[] { '╫' },
			new char[] { '╢' },
			new char[] { '╟' },
			new char[] { '⧉' },
			new char[] { '╕' },
			new char[] { '╒' },
			new char[] { '┐' },
			new char[] { '┌' },
			new char[] { '─' },
			new char[] { '╥' },
			new char[] { '╨' },
			new char[] { '┬' },
			new char[] { '┴' },
			new char[] { '⊟' },
			new char[] { '⊞' },
			new char[] { '⊠' },
			new char[] { '╛' },
			new char[] { '╘' },
			new char[] { '┘' },
			new char[] { '└' },
			new char[] { '│' },
			new char[] { '╪' },
			new char[] { '╡' },
			new char[] { '╞' },
			new char[] { '┼' },
			new char[] { '┤' },
			new char[] { '├' },
			new char[] { '‵' },
			new char[] { '\u02d8' },
			new char[] { '¦' },
			new char[] { '¦' },
			new char[] { '\ud835', '\udcb7' },
			new char[] { '⁏' },
			new char[] { '∽' },
			new char[] { '⋍' },
			new char[] { '\\' },
			new char[] { '⧅' },
			new char[] { '⟈' },
			new char[] { '•' },
			new char[] { '•' },
			new char[] { '≎' },
			new char[] { '⪮' },
			new char[] { '≏' },
			new char[] { '≏' },
			new char[] { 'ć' },
			new char[] { '∩' },
			new char[] { '⩄' },
			new char[] { '⩉' },
			new char[] { '⩋' },
			new char[] { '⩇' },
			new char[] { '⩀' },
			new char[] { '∩', '\ufe00' },
			new char[] { '⁁' },
			new char[] { 'ˇ' },
			new char[] { '⩍' },
			new char[] { 'č' },
			new char[] { 'ç' },
			new char[] { 'ç' },
			new char[] { 'ĉ' },
			new char[] { '⩌' },
			new char[] { '⩐' },
			new char[] { 'ċ' },
			new char[] { '\u00b8' },
			new char[] { '\u00b8' },
			new char[] { '⦲' },
			new char[] { '¢' },
			new char[] { '¢' },
			new char[] { '·' },
			new char[] { '\ud835', '\udd20' },
			new char[] { 'ч' },
			new char[] { '✓' },
			new char[] { '✓' },
			new char[] { 'χ' },
			new char[] { '○' },
			new char[] { '⧃' },
			new char[] { 'ˆ' },
			new char[] { '≗' },
			new char[] { '↺' },
			new char[] { '↻' },
			new char[] { '®' },
			new char[] { 'Ⓢ' },
			new char[] { '⊛' },
			new char[] { '⊚' },
			new char[] { '⊝' },
			new char[] { '≗' },
			new char[] { '⨐' },
			new char[] { '⫯' },
			new char[] { '⧂' },
			new char[] { '♣' },
			new char[] { '♣' },
			new char[] { ':' },
			new char[] { '≔' },
			new char[] { '≔' },
			new char[] { ',' },
			new char[] { '@' },
			new char[] { '∁' },
			new char[] { '∘' },
			new char[] { '∁' },
			new char[] { 'ℂ' },
			new char[] { '≅' },
			new char[] { '⩭' },
			new char[] { '∮' },
			new char[] { '\ud835', '\udd54' },
			new char[] { '∐' },
			new char[] { '©' },
			new char[] { '©' },
			new char[] { '℗' },
			new char[] { '↵' },
			new char[] { '✗' },
			new char[] { '\ud835', '\udcb8' },
			new char[] { '⫏' },
			new char[] { '⫑' },
			new char[] { '⫐' },
			new char[] { '⫒' },
			new char[] { '⋯' },
			new char[] { '⤸' },
			new char[] { '⤵' },
			new char[] { '⋞' },
			new char[] { '⋟' },
			new char[] { '↶' },
			new char[] { '⤽' },
			new char[] { '∪' },
			new char[] { '⩈' },
			new char[] { '⩆' },
			new char[] { '⩊' },
			new char[] { '⊍' },
			new char[] { '⩅' },
			new char[] { '∪', '\ufe00' },
			new char[] { '↷' },
			new char[] { '⤼' },
			new char[] { '⋞' },
			new char[] { '⋟' },
			new char[] { '⋎' },
			new char[] { '⋏' },
			new char[] { '¤' },
			new char[] { '¤' },
			new char[] { '↶' },
			new char[] { '↷' },
			new char[] { '⋎' },
			new char[] { '⋏' },
			new char[] { '∲' },
			new char[] { '∱' },
			new char[] { '⌭' },
			new char[] { '⇓' },
			new char[] { '⥥' },
			new char[] { '†' },
			new char[] { 'ℸ' },
			new char[] { '↓' },
			new char[] { '‐' },
			new char[] { '⊣' },
			new char[] { '⤏' },
			new char[] { '\u02dd' },
			new char[] { 'ď' },
			new char[] { 'д' },
			new char[] { 'ⅆ' },
			new char[] { '‡' },
			new char[] { '⇊' },
			new char[] { '⩷' },
			new char[] { '°' },
			new char[] { '°' },
			new char[] { 'δ' },
			new char[] { '⦱' },
			new char[] { '⥿' },
			new char[] { '\ud835', '\udd21' },
			new char[] { '⇃' },
			new char[] { '⇂' },
			new char[] { '⋄' },
			new char[] { '⋄' },
			new char[] { '♦' },
			new char[] { '♦' },
			new char[] { '\u00a8' },
			new char[] { 'ϝ' },
			new char[] { '⋲' },
			new char[] { '÷' },
			new char[] { '÷' },
			new char[] { '÷' },
			new char[] { '⋇' },
			new char[] { '⋇' },
			new char[] { 'ђ' },
			new char[] { '⌞' },
			new char[] { '⌍' },
			new char[] { '$' },
			new char[] { '\ud835', '\udd55' },
			new char[] { '\u02d9' },
			new char[] { '≐' },
			new char[] { '≑' },
			new char[] { '∸' },
			new char[] { '∔' },
			new char[] { '⊡' },
			new char[] { '⌆' },
			new char[] { '↓' },
			new char[] { '⇊' },
			new char[] { '⇃' },
			new char[] { '⇂' },
			new char[] { '⤐' },
			new char[] { '⌟' },
			new char[] { '⌌' },
			new char[] { '\ud835', '\udcb9' },
			new char[] { 'ѕ' },
			new char[] { '⧶' },
			new char[] { 'đ' },
			new char[] { '⋱' },
			new char[] { '▿' },
			new char[] { '▾' },
			new char[] { '⇵' },
			new char[] { '⥯' },
			new char[] { '⦦' },
			new char[] { 'џ' },
			new char[] { '⟿' },
			new char[] { '⩷' },
			new char[] { '≑' },
			new char[] { 'é' },
			new char[] { 'é' },
			new char[] { '⩮' },
			new char[] { 'ě' },
			new char[] { '≖' },
			new char[] { 'ê' },
			new char[] { 'ê' },
			new char[] { '≕' },
			new char[] { 'э' },
			new char[] { 'ė' },
			new char[] { 'ⅇ' },
			new char[] { '≒' },
			new char[] { '\ud835', '\udd22' },
			new char[] { '⪚' },
			new char[] { 'è' },
			new char[] { 'è' },
			new char[] { '⪖' },
			new char[] { '⪘' },
			new char[] { '⪙' },
			new char[] { '⏧' },
			new char[] { 'ℓ' },
			new char[] { '⪕' },
			new char[] { '⪗' },
			new char[] { 'ē' },
			new char[] { '∅' },
			new char[] { '∅' },
			new char[] { '∅' },
			new char[] { '\u2004' },
			new char[] { '\u2005' },
			new char[] { '\u2003' },
			new char[] { 'ŋ' },
			new char[] { '\u2002' },
			new char[] { 'ę' },
			new char[] { '\ud835', '\udd56' },
			new char[] { '⋕' },
			new char[] { '⧣' },
			new char[] { '⩱' },
			new char[] { 'ε' },
			new char[] { 'ε' },
			new char[] { 'ϵ' },
			new char[] { '≖' },
			new char[] { '≕' },
			new char[] { '≂' },
			new char[] { '⪖' },
			new char[] { '⪕' },
			new char[] { '=' },
			new char[] { '≟' },
			new char[] { '≡' },
			new char[] { '⩸' },
			new char[] { '⧥' },
			new char[] { '≓' },
			new char[] { '⥱' },
			new char[] { 'ℯ' },
			new char[] { '≐' },
			new char[] { '≂' },
			new char[] { 'η' },
			new char[] { 'ð' },
			new char[] { 'ð' },
			new char[] { 'ë' },
			new char[] { 'ë' },
			new char[] { '€' },
			new char[] { '!' },
			new char[] { '∃' },
			new char[] { 'ℰ' },
			new char[] { 'ⅇ' },
			new char[] { '≒' },
			new char[] { 'ф' },
			new char[] { '♀' },
			new char[] { 'ﬃ' },
			new char[] { 'ﬀ' },
			new char[] { 'ﬄ' },
			new char[] { '\ud835', '\udd23' },
			new char[] { 'ﬁ' },
			new char[] { 'f', 'j' },
			new char[] { '♭' },
			new char[] { 'ﬂ' },
			new char[] { '▱' },
			new char[] { 'ƒ' },
			new char[] { '\ud835', '\udd57' },
			new char[] { '∀' },
			new char[] { '⋔' },
			new char[] { '⫙' },
			new char[] { '⨍' },
			new char[] { '½' },
			new char[] { '½' },
			new char[] { '⅓' },
			new char[] { '¼' },
			new char[] { '¼' },
			new char[] { '⅕' },
			new char[] { '⅙' },
			new char[] { '⅛' },
			new char[] { '⅔' },
			new char[] { '⅖' },
			new char[] { '¾' },
			new char[] { '¾' },
			new char[] { '⅗' },
			new char[] { '⅜' },
			new char[] { '⅘' },
			new char[] { '⅚' },
			new char[] { '⅝' },
			new char[] { '⅞' },
			new char[] { '⁄' },
			new char[] { '⌢' },
			new char[] { '\ud835', '\udcbb' },
			new char[] { '≧' },
			new char[] { '⪌' },
			new char[] { 'ǵ' },
			new char[] { 'γ' },
			new char[] { 'ϝ' },
			new char[] { '⪆' },
			new char[] { 'ğ' },
			new char[] { 'ĝ' },
			new char[] { 'г' },
			new char[] { 'ġ' },
			new char[] { '≥' },
			new char[] { '⋛' },
			new char[] { '≥' },
			new char[] { '≧' },
			new char[] { '⩾' },
			new char[] { '⩾' },
			new char[] { '⪩' },
			new char[] { '⪀' },
			new char[] { '⪂' },
			new char[] { '⪄' },
			new char[] { '⋛', '\ufe00' },
			new char[] { '⪔' },
			new char[] { '\ud835', '\udd24' },
			new char[] { '≫' },
			new char[] { '⋙' },
			new char[] { 'ℷ' },
			new char[] { 'ѓ' },
			new char[] { '≷' },
			new char[] { '⪒' },
			new char[] { '⪥' },
			new char[] { '⪤' },
			new char[] { '≩' },
			new char[] { '⪊' },
			new char[] { '⪊' },
			new char[] { '⪈' },
			new char[] { '⪈' },
			new char[] { '≩' },
			new char[] { '⋧' },
			new char[] { '\ud835', '\udd58' },
			new char[] { '`' },
			new char[] { 'ℊ' },
			new char[] { '≳' },
			new char[] { '⪎' },
			new char[] { '⪐' },
			new char[] { '>' },
			new char[] { '>' },
			new char[] { '⪧' },
			new char[] { '⩺' },
			new char[] { '⋗' },
			new char[] { '⦕' },
			new char[] { '⩼' },
			new char[] { '⪆' },
			new char[] { '⥸' },
			new char[] { '⋗' },
			new char[] { '⋛' },
			new char[] { '⪌' },
			new char[] { '≷' },
			new char[] { '≳' },
			new char[] { '≩', '\ufe00' },
			new char[] { '≩', '\ufe00' },
			new char[] { '⇔' },
			new char[] { '\u200a' },
			new char[] { '½' },
			new char[] { 'ℋ' },
			new char[] { 'ъ' },
			new char[] { '↔' },
			new char[] { '⥈' },
			new char[] { '↭' },
			new char[] { 'ℏ' },
			new char[] { 'ĥ' },
			new char[] { '♥' },
			new char[] { '♥' },
			new char[] { '…' },
			new char[] { '⊹' },
			new char[] { '\ud835', '\udd25' },
			new char[] { '⤥' },
			new char[] { '⤦' },
			new char[] { '⇿' },
			new char[] { '∻' },
			new char[] { '↩' },
			new char[] { '↪' },
			new char[] { '\ud835', '\udd59' },
			new char[] { '―' },
			new char[] { '\ud835', '\udcbd' },
			new char[] { 'ℏ' },
			new char[] { 'ħ' },
			new char[] { '⁃' },
			new char[] { '‐' },
			new char[] { 'í' },
			new char[] { 'í' },
			new char[] { '\u2063' },
			new char[] { 'î' },
			new char[] { 'î' },
			new char[] { 'и' },
			new char[] { 'е' },
			new char[] { '¡' },
			new char[] { '¡' },
			new char[] { '⇔' },
			new char[] { '\ud835', '\udd26' },
			new char[] { 'ì' },
			new char[] { 'ì' },
			new char[] { 'ⅈ' },
			new char[] { '⨌' },
			new char[] { '∭' },
			new char[] { '⧜' },
			new char[] { '℩' },
			new char[] { 'ĳ' },
			new char[] { 'ī' },
			new char[] { 'ℑ' },
			new char[] { 'ℐ' },
			new char[] { 'ℑ' },
			new char[] { 'ı' },
			new char[] { '⊷' },
			new char[] { 'Ƶ' },
			new char[] { '∈' },
			new char[] { '℅' },
			new char[] { '∞' },
			new char[] { '⧝' },
			new char[] { 'ı' },
			new char[] { '∫' },
			new char[] { '⊺' },
			new char[] { 'ℤ' },
			new char[] { '⊺' },
			new char[] { '⨗' },
			new char[] { '⨼' },
			new char[] { 'ё' },
			new char[] { 'į' },
			new char[] { '\ud835', '\udd5a' },
			new char[] { 'ι' },
			new char[] { '⨼' },
			new char[] { '¿' },
			new char[] { '¿' },
			new char[] { '\ud835', '\udcbe' },
			new char[] { '∈' },
			new char[] { '⋹' },
			new char[] { '⋵' },
			new char[] { '⋴' },
			new char[] { '⋳' },
			new char[] { '∈' },
			new char[] { '\u2062' },
			new char[] { 'ĩ' },
			new char[] { 'і' },
			new char[] { 'ï' },
			new char[] { 'ï' },
			new char[] { 'ĵ' },
			new char[] { 'й' },
			new char[] { '\ud835', '\udd27' },
			new char[] { 'ȷ' },
			new char[] { '\ud835', '\udd5b' },
			new char[] { '\ud835', '\udcbf' },
			new char[] { 'ј' },
			new char[] { 'є' },
			new char[] { 'κ' },
			new char[] { 'ϰ' },
			new char[] { 'ķ' },
			new char[] { 'к' },
			new char[] { '\ud835', '\udd28' },
			new char[] { 'ĸ' },
			new char[] { 'х' },
			new char[] { 'ќ' },
			new char[] { '\ud835', '\udd5c' },
			new char[] { '\ud835', '\udcc0' },
			new char[] { '⇚' },
			new char[] { '⇐' },
			new char[] { '⤛' },
			new char[] { '⤎' },
			new char[] { '≦' },
			new char[] { '⪋' },
			new char[] { '⥢' },
			new char[] { 'ĺ' },
			new char[] { '⦴' },
			new char[] { 'ℒ' },
			new char[] { 'λ' },
			new char[] { '⟨' },
			new char[] { '⦑' },
			new char[] { '⟨' },
			new char[] { '⪅' },
			new char[] { '«' },
			new char[] { '«' },
			new char[] { '←' },
			new char[] { '⇤' },
			new char[] { '⤟' },
			new char[] { '⤝' },
			new char[] { '↩' },
			new char[] { '↫' },
			new char[] { '⤹' },
			new char[] { '⥳' },
			new char[] { '↢' },
			new char[] { '⪫' },
			new char[] { '⤙' },
			new char[] { '⪭' },
			new char[] { '⪭', '\ufe00' },
			new char[] { '⤌' },
			new char[] { '❲' },
			new char[] { '{' },
			new char[] { '[' },
			new char[] { '⦋' },
			new char[] { '⦏' },
			new char[] { '⦍' },
			new char[] { 'ľ' },
			new char[] { 'ļ' },
			new char[] { '⌈' },
			new char[] { '{' },
			new char[] { 'л' },
			new char[] { '⤶' },
			new char[] { '“' },
			new char[] { '„' },
			new char[] { '⥧' },
			new char[] { '⥋' },
			new char[] { '↲' },
			new char[] { '≤' },
			new char[] { '←' },
			new char[] { '↢' },
			new char[] { '↽' },
			new char[] { '↼' },
			new char[] { '⇇' },
			new char[] { '↔' },
			new char[] { '⇆' },
			new char[] { '⇋' },
			new char[] { '↭' },
			new char[] { '⋋' },
			new char[] { '⋚' },
			new char[] { '≤' },
			new char[] { '≦' },
			new char[] { '⩽' },
			new char[] { '⩽' },
			new char[] { '⪨' },
			new char[] { '⩿' },
			new char[] { '⪁' },
			new char[] { '⪃' },
			new char[] { '⋚', '\ufe00' },
			new char[] { '⪓' },
			new char[] { '⪅' },
			new char[] { '⋖' },
			new char[] { '⋚' },
			new char[] { '⪋' },
			new char[] { '≶' },
			new char[] { '≲' },
			new char[] { '⥼' },
			new char[] { '⌊' },
			new char[] { '\ud835', '\udd29' },
			new char[] { '≶' },
			new char[] { '⪑' },
			new char[] { '↽' },
			new char[] { '↼' },
			new char[] { '⥪' },
			new char[] { '▄' },
			new char[] { 'љ' },
			new char[] { '≪' },
			new char[] { '⇇' },
			new char[] { '⌞' },
			new char[] { '⥫' },
			new char[] { '◺' },
			new char[] { 'ŀ' },
			new char[] { '⎰' },
			new char[] { '⎰' },
			new char[] { '≨' },
			new char[] { '⪉' },
			new char[] { '⪉' },
			new char[] { '⪇' },
			new char[] { '⪇' },
			new char[] { '≨' },
			new char[] { '⋦' },
			new char[] { '⟬' },
			new char[] { '⇽' },
			new char[] { '⟦' },
			new char[] { '⟵' },
			new char[] { '⟷' },
			new char[] { '⟼' },
			new char[] { '⟶' },
			new char[] { '↫' },
			new char[] { '↬' },
			new char[] { '⦅' },
			new char[] { '\ud835', '\udd5d' },
			new char[] { '⨭' },
			new char[] { '⨴' },
			new char[] { '∗' },
			new char[] { '_' },
			new char[] { '◊' },
			new char[] { '◊' },
			new char[] { '⧫' },
			new char[] { '(' },
			new char[] { '⦓' },
			new char[] { '⇆' },
			new char[] { '⌟' },
			new char[] { '⇋' },
			new char[] { '⥭' },
			new char[] { '\u200e' },
			new char[] { '⊿' },
			new char[] { '‹' },
			new char[] { '\ud835', '\udcc1' },
			new char[] { '↰' },
			new char[] { '≲' },
			new char[] { '⪍' },
			new char[] { '⪏' },
			new char[] { '[' },
			new char[] { '‘' },
			new char[] { '‚' },
			new char[] { 'ł' },
			new char[] { '<' },
			new char[] { '<' },
			new char[] { '⪦' },
			new char[] { '⩹' },
			new char[] { '⋖' },
			new char[] { '⋋' },
			new char[] { '⋉' },
			new char[] { '⥶' },
			new char[] { '⩻' },
			new char[] { '⦖' },
			new char[] { '◃' },
			new char[] { '⊴' },
			new char[] { '◂' },
			new char[] { '⥊' },
			new char[] { '⥦' },
			new char[] { '≨', '\ufe00' },
			new char[] { '≨', '\ufe00' },
			new char[] { '∺' },
			new char[] { '\u00af' },
			new char[] { '\u00af' },
			new char[] { '♂' },
			new char[] { '✠' },
			new char[] { '✠' },
			new char[] { '↦' },
			new char[] { '↦' },
			new char[] { '↧' },
			new char[] { '↤' },
			new char[] { '↥' },
			new char[] { '▮' },
			new char[] { '⨩' },
			new char[] { 'м' },
			new char[] { '—' },
			new char[] { '∡' },
			new char[] { '\ud835', '\udd2a' },
			new char[] { '℧' },
			new char[] { 'µ' },
			new char[] { 'µ' },
			new char[] { '∣' },
			new char[] { '*' },
			new char[] { '⫰' },
			new char[] { '·' },
			new char[] { '·' },
			new char[] { '−' },
			new char[] { '⊟' },
			new char[] { '∸' },
			new char[] { '⨪' },
			new char[] { '⫛' },
			new char[] { '…' },
			new char[] { '∓' },
			new char[] { '⊧' },
			new char[] { '\ud835', '\udd5e' },
			new char[] { '∓' },
			new char[] { '\ud835', '\udcc2' },
			new char[] { '∾' },
			new char[] { 'μ' },
			new char[] { '⊸' },
			new char[] { '⊸' },
			new char[] { '⋙', '\u0338' },
			new char[] { '≫', '\u20d2' },
			new char[] { '≫', '\u0338' },
			new char[] { '⇍' },
			new char[] { '⇎' },
			new char[] { '⋘', '\u0338' },
			new char[] { '≪', '\u20d2' },
			new char[] { '≪', '\u0338' },
			new char[] { '⇏' },
			new char[] { '⊯' },
			new char[] { '⊮' },
			new char[] { '∇' },
			new char[] { 'ń' },
			new char[] { '∠', '\u20d2' },
			new char[] { '≉' },
			new char[] { '⩰', '\u0338' },
			new char[] { '≋', '\u0338' },
			new char[] { 'ŉ' },
			new char[] { '≉' },
			new char[] { '♮' },
			new char[] { '♮' },
			new char[] { 'ℕ' },
			new char[] { '\u00a0' },
			new char[] { '\u00a0' },
			new char[] { '≎', '\u0338' },
			new char[] { '≏', '\u0338' },
			new char[] { '⩃' },
			new char[] { 'ň' },
			new char[] { 'ņ' },
			new char[] { '≇' },
			new char[] { '⩭', '\u0338' },
			new char[] { '⩂' },
			new char[] { 'н' },
			new char[] { '–' },
			new char[] { '≠' },
			new char[] { '⇗' },
			new char[] { '⤤' },
			new char[] { '↗' },
			new char[] { '↗' },
			new char[] { '≐', '\u0338' },
			new char[] { '≢' },
			new char[] { '⤨' },
			new char[] { '≂', '\u0338' },
			new char[] { '∄' },
			new char[] { '∄' },
			new char[] { '\ud835', '\udd2b' },
			new char[] { '≧', '\u0338' },
			new char[] { '≱' },
			new char[] { '≱' },
			new char[] { '≧', '\u0338' },
			new char[] { '⩾', '\u0338' },
			new char[] { '⩾', '\u0338' },
			new char[] { '≵' },
			new char[] { '≯' },
			new char[] { '≯' },
			new char[] { '⇎' },
			new char[] { '↮' },
			new char[] { '⫲' },
			new char[] { '∋' },
			new char[] { '⋼' },
			new char[] { '⋺' },
			new char[] { '∋' },
			new char[] { 'њ' },
			new char[] { '⇍' },
			new char[] { '≦', '\u0338' },
			new char[] { '↚' },
			new char[] { '‥' },
			new char[] { '≰' },
			new char[] { '↚' },
			new char[] { '↮' },
			new char[] { '≰' },
			new char[] { '≦', '\u0338' },
			new char[] { '⩽', '\u0338' },
			new char[] { '⩽', '\u0338' },
			new char[] { '≮' },
			new char[] { '≴' },
			new char[] { '≮' },
			new char[] { '⋪' },
			new char[] { '⋬' },
			new char[] { '∤' },
			new char[] { '\ud835', '\udd5f' },
			new char[] { '¬' },
			new char[] { '¬' },
			new char[] { '∉' },
			new char[] { '⋹', '\u0338' },
			new char[] { '⋵', '\u0338' },
			new char[] { '∉' },
			new char[] { '⋷' },
			new char[] { '⋶' },
			new char[] { '∌' },
			new char[] { '∌' },
			new char[] { '⋾' },
			new char[] { '⋽' },
			new char[] { '∦' },
			new char[] { '∦' },
			new char[] { '⫽', '\u20e5' },
			new char[] { '∂', '\u0338' },
			new char[] { '⨔' },
			new char[] { '⊀' },
			new char[] { '⋠' },
			new char[] { '⪯', '\u0338' },
			new char[] { '⊀' },
			new char[] { '⪯', '\u0338' },
			new char[] { '⇏' },
			new char[] { '↛' },
			new char[] { '⤳', '\u0338' },
			new char[] { '↝', '\u0338' },
			new char[] { '↛' },
			new char[] { '⋫' },
			new char[] { '⋭' },
			new char[] { '⊁' },
			new char[] { '⋡' },
			new char[] { '⪰', '\u0338' },
			new char[] { '\ud835', '\udcc3' },
			new char[] { '∤' },
			new char[] { '∦' },
			new char[] { '≁' },
			new char[] { '≄' },
			new char[] { '≄' },
			new char[] { '∤' },
			new char[] { '∦' },
			new char[] { '⋢' },
			new char[] { '⋣' },
			new char[] { '⊄' },
			new char[] { '⫅', '\u0338' },
			new char[] { '⊈' },
			new char[] { '⊂', '\u20d2' },
			new char[] { '⊈' },
			new char[] { '⫅', '\u0338' },
			new char[] { '⊁' },
			new char[] { '⪰', '\u0338' },
			new char[] { '⊅' },
			new char[] { '⫆', '\u0338' },
			new char[] { '⊉' },
			new char[] { '⊃', '\u20d2' },
			new char[] { '⊉' },
			new char[] { '⫆', '\u0338' },
			new char[] { '≹' },
			new char[] { 'ñ' },
			new char[] { 'ñ' },
			new char[] { '≸' },
			new char[] { '⋪' },
			new char[] { '⋬' },
			new char[] { '⋫' },
			new char[] { '⋭' },
			new char[] { 'ν' },
			new char[] { '#' },
			new char[] { '№' },
			new char[] { '\u2007' },
			new char[] { '⊭' },
			new char[] { '⤄' },
			new char[] { '≍', '\u20d2' },
			new char[] { '⊬' },
			new char[] { '≥', '\u20d2' },
			new char[] { '>', '\u20d2' },
			new char[] { '⧞' },
			new char[] { '⤂' },
			new char[] { '≤', '\u20d2' },
			new char[] { '<', '\u20d2' },
			new char[] { '⊴', '\u20d2' },
			new char[] { '⤃' },
			new char[] { '⊵', '\u20d2' },
			new char[] { '∼', '\u20d2' },
			new char[] { '⇖' },
			new char[] { '⤣' },
			new char[] { '↖' },
			new char[] { '↖' },
			new char[] { '⤧' },
			new char[] { 'Ⓢ' },
			new char[] { 'ó' },
			new char[] { 'ó' },
			new char[] { '⊛' },
			new char[] { '⊚' },
			new char[] { 'ô' },
			new char[] { 'ô' },
			new char[] { 'о' },
			new char[] { '⊝' },
			new char[] { 'ő' },
			new char[] { '⨸' },
			new char[] { '⊙' },
			new char[] { '⦼' },
			new char[] { 'œ' },
			new char[] { '⦿' },
			new char[] { '\ud835', '\udd2c' },
			new char[] { '\u02db' },
			new char[] { 'ò' },
			new char[] { 'ò' },
			new char[] { '⧁' },
			new char[] { '⦵' },
			new char[] { 'Ω' },
			new char[] { '∮' },
			new char[] { '↺' },
			new char[] { '⦾' },
			new char[] { '⦻' },
			new char[] { '‾' },
			new char[] { '⧀' },
			new char[] { 'ō' },
			new char[] { 'ω' },
			new char[] { 'ο' },
			new char[] { '⦶' },
			new char[] { '⊖' },
			new char[] { '\ud835', '\udd60' },
			new char[] { '⦷' },
			new char[] { '⦹' },
			new char[] { '⊕' },
			new char[] { '∨' },
			new char[] { '↻' },
			new char[] { '⩝' },
			new char[] { 'ℴ' },
			new char[] { 'ℴ' },
			new char[] { 'ª' },
			new char[] { 'ª' },
			new char[] { 'º' },
			new char[] { 'º' },
			new char[] { '⊶' },
			new char[] { '⩖' },
			new char[] { '⩗' },
			new char[] { '⩛' },
			new char[] { 'ℴ' },
			new char[] { 'ø' },
			new char[] { 'ø' },
			new char[] { '⊘' },
			new char[] { 'õ' },
			new char[] { 'õ' },
			new char[] { '⊗' },
			new char[] { '⨶' },
			new char[] { 'ö' },
			new char[] { 'ö' },
			new char[] { '⌽' },
			new char[] { '∥' },
			new char[] { '¶' },
			new char[] { '¶' },
			new char[] { '∥' },
			new char[] { '⫳' },
			new char[] { '⫽' },
			new char[] { '∂' },
			new char[] { 'п' },
			new char[] { '%' },
			new char[] { '.' },
			new char[] { '‰' },
			new char[] { '⊥' },
			new char[] { '‱' },
			new char[] { '\ud835', '\udd2d' },
			new char[] { 'φ' },
			new char[] { 'ϕ' },
			new char[] { 'ℳ' },
			new char[] { '☎' },
			new char[] { 'π' },
			new char[] { '⋔' },
			new char[] { 'ϖ' },
			new char[] { 'ℏ' },
			new char[] { 'ℎ' },
			new char[] { 'ℏ' },
			new char[] { '+' },
			new char[] { '⨣' },
			new char[] { '⊞' },
			new char[] { '⨢' },
			new char[] { '∔' },
			new char[] { '⨥' },
			new char[] { '⩲' },
			new char[] { '±' },
			new char[] { '±' },
			new char[] { '⨦' },
			new char[] { '⨧' },
			new char[] { '±' },
			new char[] { '⨕' },
			new char[] { '\ud835', '\udd61' },
			new char[] { '£' },
			new char[] { '£' },
			new char[] { '≺' },
			new char[] { '⪳' },
			new char[] { '⪷' },
			new char[] { '≼' },
			new char[] { '⪯' },
			new char[] { '≺' },
			new char[] { '⪷' },
			new char[] { '≼' },
			new char[] { '⪯' },
			new char[] { '⪹' },
			new char[] { '⪵' },
			new char[] { '⋨' },
			new char[] { '≾' },
			new char[] { '′' },
			new char[] { 'ℙ' },
			new char[] { '⪵' },
			new char[] { '⪹' },
			new char[] { '⋨' },
			new char[] { '∏' },
			new char[] { '⌮' },
			new char[] { '⌒' },
			new char[] { '⌓' },
			new char[] { '∝' },
			new char[] { '∝' },
			new char[] { '≾' },
			new char[] { '⊰' },
			new char[] { '\ud835', '\udcc5' },
			new char[] { 'ψ' },
			new char[] { '\u2008' },
			new char[] { '\ud835', '\udd2e' },
			new char[] { '⨌' },
			new char[] { '\ud835', '\udd62' },
			new char[] { '⁗' },
			new char[] { '\ud835', '\udcc6' },
			new char[] { 'ℍ' },
			new char[] { '⨖' },
			new char[] { '?' },
			new char[] { '≟' },
			new char[] { '"' },
			new char[] { '"' },
			new char[] { '⇛' },
			new char[] { '⇒' },
			new char[] { '⤜' },
			new char[] { '⤏' },
			new char[] { '⥤' },
			new char[] { '∽', '\u0331' },
			new char[] { 'ŕ' },
			new char[] { '√' },
			new char[] { '⦳' },
			new char[] { '⟩' },
			new char[] { '⦒' },
			new char[] { '⦥' },
			new char[] { '⟩' },
			new char[] { '»' },
			new char[] { '»' },
			new char[] { '→' },
			new char[] { '⥵' },
			new char[] { '⇥' },
			new char[] { '⤠' },
			new char[] { '⤳' },
			new char[] { '⤞' },
			new char[] { '↪' },
			new char[] { '↬' },
			new char[] { '⥅' },
			new char[] { '⥴' },
			new char[] { '↣' },
			new char[] { '↝' },
			new char[] { '⤚' },
			new char[] { '∶' },
			new char[] { 'ℚ' },
			new char[] { '⤍' },
			new char[] { '❳' },
			new char[] { '}' },
			new char[] { ']' },
			new char[] { '⦌' },
			new char[] { '⦎' },
			new char[] { '⦐' },
			new char[] { 'ř' },
			new char[] { 'ŗ' },
			new char[] { '⌉' },
			new char[] { '}' },
			new char[] { 'р' },
			new char[] { '⤷' },
			new char[] { '⥩' },
			new char[] { '”' },
			new char[] { '”' },
			new char[] { '↳' },
			new char[] { 'ℜ' },
			new char[] { 'ℛ' },
			new char[] { 'ℜ' },
			new char[] { 'ℝ' },
			new char[] { '▭' },
			new char[] { '®' },
			new char[] { '®' },
			new char[] { '⥽' },
			new char[] { '⌋' },
			new char[] { '\ud835', '\udd2f' },
			new char[] { '⇁' },
			new char[] { '⇀' },
			new char[] { '⥬' },
			new char[] { 'ρ' },
			new char[] { 'ϱ' },
			new char[] { '→' },
			new char[] { '↣' },
			new char[] { '⇁' },
			new char[] { '⇀' },
			new char[] { '⇄' },
			new char[] { '⇌' },
			new char[] { '⇉' },
			new char[] { '↝' },
			new char[] { '⋌' },
			new char[] { '\u02da' },
			new char[] { '≓' },
			new char[] { '⇄' },
			new char[] { '⇌' },
			new char[] { '\u200f' },
			new char[] { '⎱' },
			new char[] { '⎱' },
			new char[] { '⫮' },
			new char[] { '⟭' },
			new char[] { '⇾' },
			new char[] { '⟧' },
			new char[] { '⦆' },
			new char[] { '\ud835', '\udd63' },
			new char[] { '⨮' },
			new char[] { '⨵' },
			new char[] { ')' },
			new char[] { '⦔' },
			new char[] { '⨒' },
			new char[] { '⇉' },
			new char[] { '›' },
			new char[] { '\ud835', '\udcc7' },
			new char[] { '↱' },
			new char[] { ']' },
			new char[] { '’' },
			new char[] { '’' },
			new char[] { '⋌' },
			new char[] { '⋊' },
			new char[] { '▹' },
			new char[] { '⊵' },
			new char[] { '▸' },
			new char[] { '⧎' },
			new char[] { '⥨' },
			new char[] { '℞' },
			new char[] { 'ś' },
			new char[] { '‚' },
			new char[] { '≻' },
			new char[] { '⪴' },
			new char[] { '⪸' },
			new char[] { 'š' },
			new char[] { '≽' },
			new char[] { '⪰' },
			new char[] { 'ş' },
			new char[] { 'ŝ' },
			new char[] { '⪶' },
			new char[] { '⪺' },
			new char[] { '⋩' },
			new char[] { '⨓' },
			new char[] { '≿' },
			new char[] { 'с' },
			new char[] { '⋅' },
			new char[] { '⊡' },
			new char[] { '⩦' },
			new char[] { '⇘' },
			new char[] { '⤥' },
			new char[] { '↘' },
			new char[] { '↘' },
			new char[] { '§' },
			new char[] { '§' },
			new char[] { ';' },
			new char[] { '⤩' },
			new char[] { '∖' },
			new char[] { '∖' },
			new char[] { '✶' },
			new char[] { '\ud835', '\udd30' },
			new char[] { '⌢' },
			new char[] { '♯' },
			new char[] { 'щ' },
			new char[] { 'ш' },
			new char[] { '∣' },
			new char[] { '∥' },
			new char[] { '\u00ad' },
			new char[] { '\u00ad' },
			new char[] { 'σ' },
			new char[] { 'ς' },
			new char[] { 'ς' },
			new char[] { '∼' },
			new char[] { '⩪' },
			new char[] { '≃' },
			new char[] { '≃' },
			new char[] { '⪞' },
			new char[] { '⪠' },
			new char[] { '⪝' },
			new char[] { '⪟' },
			new char[] { '≆' },
			new char[] { '⨤' },
			new char[] { '⥲' },
			new char[] { '←' },
			new char[] { '∖' },
			new char[] { '⨳' },
			new char[] { '⧤' },
			new char[] { '∣' },
			new char[] { '⌣' },
			new char[] { '⪪' },
			new char[] { '⪬' },
			new char[] { '⪬', '\ufe00' },
			new char[] { 'ь' },
			new char[] { '/' },
			new char[] { '⧄' },
			new char[] { '⌿' },
			new char[] { '\ud835', '\udd64' },
			new char[] { '♠' },
			new char[] { '♠' },
			new char[] { '∥' },
			new char[] { '⊓' },
			new char[] { '⊓', '\ufe00' },
			new char[] { '⊔' },
			new char[] { '⊔', '\ufe00' },
			new char[] { '⊏' },
			new char[] { '⊑' },
			new char[] { '⊏' },
			new char[] { '⊑' },
			new char[] { '⊐' },
			new char[] { '⊒' },
			new char[] { '⊐' },
			new char[] { '⊒' },
			new char[] { '□' },
			new char[] { '□' },
			new char[] { '▪' },
			new char[] { '▪' },
			new char[] { '→' },
			new char[] { '\ud835', '\udcc8' },
			new char[] { '∖' },
			new char[] { '⌣' },
			new char[] { '⋆' },
			new char[] { '☆' },
			new char[] { '★' },
			new char[] { 'ϵ' },
			new char[] { 'ϕ' },
			new char[] { '\u00af' },
			new char[] { '⊂' },
			new char[] { '⫅' },
			new char[] { '⪽' },
			new char[] { '⊆' },
			new char[] { '⫃' },
			new char[] { '⫁' },
			new char[] { '⫋' },
			new char[] { '⊊' },
			new char[] { '⪿' },
			new char[] { '⥹' },
			new char[] { '⊂' },
			new char[] { '⊆' },
			new char[] { '⫅' },
			new char[] { '⊊' },
			new char[] { '⫋' },
			new char[] { '⫇' },
			new char[] { '⫕' },
			new char[] { '⫓' },
			new char[] { '≻' },
			new char[] { '⪸' },
			new char[] { '≽' },
			new char[] { '⪰' },
			new char[] { '⪺' },
			new char[] { '⪶' },
			new char[] { '⋩' },
			new char[] { '≿' },
			new char[] { '∑' },
			new char[] { '♪' },
			new char[] { '¹' },
			new char[] { '¹' },
			new char[] { '²' },
			new char[] { '²' },
			new char[] { '³' },
			new char[] { '³' },
			new char[] { '⊃' },
			new char[] { '⫆' },
			new char[] { '⪾' },
			new char[] { '⫘' },
			new char[] { '⊇' },
			new char[] { '⫄' },
			new char[] { '⟉' },
			new char[] { '⫗' },
			new char[] { '⥻' },
			new char[] { '⫂' },
			new char[] { '⫌' },
			new char[] { '⊋' },
			new char[] { '⫀' },
			new char[] { '⊃' },
			new char[] { '⊇' },
			new char[] { '⫆' },
			new char[] { '⊋' },
			new char[] { '⫌' },
			new char[] { '⫈' },
			new char[] { '⫔' },
			new char[] { '⫖' },
			new char[] { '⇙' },
			new char[] { '⤦' },
			new char[] { '↙' },
			new char[] { '↙' },
			new char[] { '⤪' },
			new char[] { 'ß' },
			new char[] { 'ß' },
			new char[] { '⌖' },
			new char[] { 'τ' },
			new char[] { '⎴' },
			new char[] { 'ť' },
			new char[] { 'ţ' },
			new char[] { 'т' },
			new char[] { '\u20db' },
			new char[] { '⌕' },
			new char[] { '\ud835', '\udd31' },
			new char[] { '∴' },
			new char[] { '∴' },
			new char[] { 'θ' },
			new char[] { 'ϑ' },
			new char[] { 'ϑ' },
			new char[] { '≈' },
			new char[] { '∼' },
			new char[] { '\u2009' },
			new char[] { '≈' },
			new char[] { '∼' },
			new char[] { 'þ' },
			new char[] { 'þ' },
			new char[] { '\u02dc' },
			new char[] { '×' },
			new char[] { '×' },
			new char[] { '⊠' },
			new char[] { '⨱' },
			new char[] { '⨰' },
			new char[] { '∭' },
			new char[] { '⤨' },
			new char[] { '⊤' },
			new char[] { '⌶' },
			new char[] { '⫱' },
			new char[] { '\ud835', '\udd65' },
			new char[] { '⫚' },
			new char[] { '⤩' },
			new char[] { '‴' },
			new char[] { '™' },
			new char[] { '▵' },
			new char[] { '▿' },
			new char[] { '◃' },
			new char[] { '⊴' },
			new char[] { '≜' },
			new char[] { '▹' },
			new char[] { '⊵' },
			new char[] { '◬' },
			new char[] { '≜' },
			new char[] { '⨺' },
			new char[] { '⨹' },
			new char[] { '⧍' },
			new char[] { '⨻' },
			new char[] { '⏢' },
			new char[] { '\ud835', '\udcc9' },
			new char[] { 'ц' },
			new char[] { 'ћ' },
			new char[] { 'ŧ' },
			new char[] { '≬' },
			new char[] { '↞' },
			new char[] { '↠' },
			new char[] { '⇑' },
			new char[] { '⥣' },
			new char[] { 'ú' },
			new char[] { 'ú' },
			new char[] { '↑' },
			new char[] { 'ў' },
			new char[] { 'ŭ' },
			new char[] { 'û' },
			new char[] { 'û' },
			new char[] { 'у' },
			new char[] { '⇅' },
			new char[] { 'ű' },
			new char[] { '⥮' },
			new char[] { '⥾' },
			new char[] { '\ud835', '\udd32' },
			new char[] { 'ù' },
			new char[] { 'ù' },
			new char[] { '↿' },
			new char[] { '↾' },
			new char[] { '▀' },
			new char[] { '⌜' },
			new char[] { '⌜' },
			new char[] { '⌏' },
			new char[] { '◸' },
			new char[] { 'ū' },
			new char[] { '\u00a8' },
			new char[] { '\u00a8' },
			new char[] { 'ų' },
			new char[] { '\ud835', '\udd66' },
			new char[] { '↑' },
			new char[] { '↕' },
			new char[] { '↿' },
			new char[] { '↾' },
			new char[] { '⊎' },
			new char[] { 'υ' },
			new char[] { 'ϒ' },
			new char[] { 'υ' },
			new char[] { '⇈' },
			new char[] { '⌝' },
			new char[] { '⌝' },
			new char[] { '⌎' },
			new char[] { 'ů' },
			new char[] { '◹' },
			new char[] { '\ud835', '\udcca' },
			new char[] { '⋰' },
			new char[] { 'ũ' },
			new char[] { '▵' },
			new char[] { '▴' },
			new char[] { '⇈' },
			new char[] { 'ü' },
			new char[] { 'ü' },
			new char[] { '⦧' },
			new char[] { '⇕' },
			new char[] { '⫨' },
			new char[] { '⫩' },
			new char[] { '⊨' },
			new char[] { '⦜' },
			new char[] { 'ϵ' },
			new char[] { 'ϰ' },
			new char[] { '∅' },
			new char[] { 'ϕ' },
			new char[] { 'ϖ' },
			new char[] { '∝' },
			new char[] { '↕' },
			new char[] { 'ϱ' },
			new char[] { 'ς' },
			new char[] { '⊊', '\ufe00' },
			new char[] { '⫋', '\ufe00' },
			new char[] { '⊋', '\ufe00' },
			new char[] { '⫌', '\ufe00' },
			new char[] { 'ϑ' },
			new char[] { '⊲' },
			new char[] { '⊳' },
			new char[] { 'в' },
			new char[] { '⊢' },
			new char[] { '∨' },
			new char[] { '⊻' },
			new char[] { '≚' },
			new char[] { '⋮' },
			new char[] { '|' },
			new char[] { '|' },
			new char[] { '\ud835', '\udd33' },
			new char[] { '⊲' },
			new char[] { '⊂', '\u20d2' },
			new char[] { '⊃', '\u20d2' },
			new char[] { '\ud835', '\udd67' },
			new char[] { '∝' },
			new char[] { '⊳' },
			new char[] { '\ud835', '\udccb' },
			new char[] { '⫋', '\ufe00' },
			new char[] { '⊊', '\ufe00' },
			new char[] { '⫌', '\ufe00' },
			new char[] { '⊋', '\ufe00' },
			new char[] { '⦚' },
			new char[] { 'ŵ' },
			new char[] { '⩟' },
			new char[] { '∧' },
			new char[] { '≙' },
			new char[] { '℘' },
			new char[] { '\ud835', '\udd34' },
			new char[] { '\ud835', '\udd68' },
			new char[] { '℘' },
			new char[] { '≀' },
			new char[] { '≀' },
			new char[] { '\ud835', '\udccc' },
			new char[] { '⋂' },
			new char[] { '◯' },
			new char[] { '⋃' },
			new char[] { '▽' },
			new char[] { '\ud835', '\udd35' },
			new char[] { '⟺' },
			new char[] { '⟷' },
			new char[] { 'ξ' },
			new char[] { '⟸' },
			new char[] { '⟵' },
			new char[] { '⟼' },
			new char[] { '⋻' },
			new char[] { '⨀' },
			new char[] { '\ud835', '\udd69' },
			new char[] { '⨁' },
			new char[] { '⨂' },
			new char[] { '⟹' },
			new char[] { '⟶' },
			new char[] { '\ud835', '\udccd' },
			new char[] { '⨆' },
			new char[] { '⨄' },
			new char[] { '△' },
			new char[] { '⋁' },
			new char[] { '⋀' },
			new char[] { 'ý' },
			new char[] { 'ý' },
			new char[] { 'я' },
			new char[] { 'ŷ' },
			new char[] { 'ы' },
			new char[] { '¥' },
			new char[] { '¥' },
			new char[] { '\ud835', '\udd36' },
			new char[] { 'ї' },
			new char[] { '\ud835', '\udd6a' },
			new char[] { '\ud835', '\udcce' },
			new char[] { 'ю' },
			new char[] { 'ÿ' },
			new char[] { 'ÿ' },
			new char[] { 'ź' },
			new char[] { 'ž' },
			new char[] { 'з' },
			new char[] { 'ż' },
			new char[] { 'ℨ' },
			new char[] { 'ζ' },
			new char[] { '\ud835', '\udd37' },
			new char[] { 'ж' },
			new char[] { '⇝' },
			new char[] { '\ud835', '\udd6b' },
			new char[] { '\ud835', '\udccf' },
			new char[] { '\u200d' },
			new char[] { '\u200c' }
		};

		internal static readonly char[][] WINDOWS_1252 = new char[][]
		{
			new char[] { '€' },
			new char[] { '\u0081' },
			new char[] { '‚' },
			new char[] { 'ƒ' },
			new char[] { '„' },
			new char[] { '…' },
			new char[] { '†' },
			new char[] { '‡' },
			new char[] { 'ˆ' },
			new char[] { '‰' },
			new char[] { 'Š' },
			new char[] { '‹' },
			new char[] { 'Œ' },
			new char[] { '\u008d' },
			new char[] { 'Ž' },
			new char[] { '\u008f' },
			new char[] { '\u0090' },
			new char[] { '‘' },
			new char[] { '’' },
			new char[] { '“' },
			new char[] { '”' },
			new char[] { '•' },
			new char[] { '–' },
			new char[] { '—' },
			new char[] { '\u02dc' },
			new char[] { '™' },
			new char[] { 'š' },
			new char[] { '›' },
			new char[] { 'œ' },
			new char[] { '\u009d' },
			new char[] { 'ž' },
			new char[] { 'Ÿ' }
		};
	}
}
