using System;
using System.Collections.Generic;

namespace Telerik.Windows.Documents.Spreadsheet.Maths
{
	sealed class AreaConverter
	{
		static AreaConverter()
		{
			Dictionary<Tuple<AreaUnit, AreaUnit>, Func<double, double>> dictionary = new Dictionary<Tuple<AreaUnit, AreaUnit>, Func<double, double>>();
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.InternationalAcre), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.USSurveyAcre), (double v) => v * 0.999996000004);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareAngstrom), (double v) => v * 4.0468564224E+23);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.Are), (double v) => v * 40.468564224);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareFeet), (double v) => v * 43560.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.Hectare), (double v) => v * 0.40468564224);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareInches), (double v) => v * 6272640.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareLightYear), (double v) => v * 4.52135342619881E-29);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareMeters), (double v) => v * 4046.8564224);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.Morgen), (double v) => v * 1.61874256896);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareMiles), (double v) => v * 0.0015625);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareNauticalMiles), (double v) => v * 0.0011798745452934);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquarePica), (double v) => v * 32517365760.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.InternationalAcre, AreaUnit.SquareYards), (double v) => v * 4840.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.InternationalAcre), (double v) => v * 1.000004000012);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.USSurveyAcre), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareAngstrom), (double v) => v * 4.04687260987425E+23);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.Are), (double v) => v * 40.4687260987425);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareFeet), (double v) => v * 43560.1742405227);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.Hectare), (double v) => v * 0.404687260987425);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareInches), (double v) => v * 6272665.09063527);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareLightYear), (double v) => v * 4.52137151166678E-29);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareMeters), (double v) => v * 4046.87260987425);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.Morgen), (double v) => v * 1.6187490439497);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareMiles), (double v) => v * 0.00156250625001875);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareNauticalMiles), (double v) => v * 0.00117987926480574);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquarePica), (double v) => v * 32517495829.8533);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.USSurveyAcre, AreaUnit.SquareYards), (double v) => v * 4840.01936005808);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.InternationalAcre), (double v) => v * 2.47105381467165E-24);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.USSurveyAcre), (double v) => v * 2.47104393046628E-24);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareAngstrom), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.Are), (double v) => v * 1E-22);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareFeet), (double v) => v * 1.07639104167097E-19);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.Hectare), (double v) => v * 1E-24);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareInches), (double v) => v * 1.5500031000062E-17);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareLightYear), (double v) => v * 1.11725076312873E-52);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareMeters), (double v) => v * 1E-20);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.Morgen), (double v) => v * 4E-24);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareMiles), (double v) => v * 3.86102158542446E-27);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareNauticalMiles), (double v) => v * 2.91553349598123E-27);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquarePica), (double v) => v * 8.03521607043214E-14);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareAngstrom, AreaUnit.SquareYards), (double v) => v * 1.19599004630108E-20);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.InternationalAcre), (double v) => v * 0.0247105381467165);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.USSurveyAcre), (double v) => v * 0.0247104393046628);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareAngstrom), (double v) => v * 1E+22);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.Are), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareFeet), (double v) => v * 1076.39104167097);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.Hectare), (double v) => v * 0.01);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareInches), (double v) => v * 155000.31000062);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareLightYear), (double v) => v * 1.11725076312873E-30);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareMeters), (double v) => v * 100.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.Morgen), (double v) => v * 0.04);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareMiles), (double v) => v * 3.86102158542446E-05);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareNauticalMiles), (double v) => v * 2.91553349598123E-05);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquarePica), (double v) => v * 803521607.043214);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Are, AreaUnit.SquareYards), (double v) => v * 119.599004630108);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.InternationalAcre), (double v) => v * 2.29568411386593E-05);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.USSurveyAcre), (double v) => v * 2.29567493113866E-05);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareAngstrom), (double v) => v * 9.290304E+18);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.Are), (double v) => v * 0.0009290304);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareFeet), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.Hectare), (double v) => v * 9.290304E-06);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareInches), (double v) => v * 144.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareLightYear), (double v) => v * 1.03795992336979E-33);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareMeters), (double v) => v * 0.09290304);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.Morgen), (double v) => v * 3.7161216E-05);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareMiles), (double v) => v * 3.58700642791552E-08);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareNauticalMiles), (double v) => v * 2.70861924998484E-08);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquarePica), (double v) => v * 746496.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareFeet, AreaUnit.SquareYards), (double v) => v * 0.111111111111111);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.InternationalAcre), (double v) => v * 2.47105381467165);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.USSurveyAcre), (double v) => v * 2.47104393046628);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareAngstrom), (double v) => v * 1E+24);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.Are), (double v) => v * 100.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareFeet), (double v) => v * 107639.104167097);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.Hectare), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareInches), (double v) => v * 15500031.000062);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareLightYear), (double v) => v * 1.11725076312873E-28);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareMeters), (double v) => v * 10000.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.Morgen), (double v) => v * 4.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareMiles), (double v) => v * 0.00386102158542446);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareNauticalMiles), (double v) => v * 0.00291553349598123);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquarePica), (double v) => v * 80352160704.3214);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Hectare, AreaUnit.SquareYards), (double v) => v * 11959.9004630108);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.InternationalAcre), (double v) => v * 1.59422507907356E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.USSurveyAcre), (double v) => v * 1.59421870217962E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareAngstrom), (double v) => v * 64516000000000000.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.Are), (double v) => v * 6.4516E-06);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareFeet), (double v) => v * 0.00694444444444444);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.Hectare), (double v) => v * 6.4516E-08);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareInches), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareLightYear), (double v) => v * 7.20805502340133E-36);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareMeters), (double v) => v * 0.00064516);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.Morgen), (double v) => v * 2.58064E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareMiles), (double v) => v * 2.49097668605244E-10);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareNauticalMiles), (double v) => v * 1.88098559026725E-10);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquarePica), (double v) => v * 5184.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareInches, AreaUnit.SquareYards), (double v) => v * 0.000771604938271605);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.InternationalAcre), (double v) => v * 2.21172712180724E+28);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.USSurveyAcre), (double v) => v * 2.2117182749076E+28);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareAngstrom), (double v) => v * 8.95054210748189E+51);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.Are), (double v) => v * 8.95054210748189E+29);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareFeet), (double v) => v * 9.63428334259233E+32);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.Hectare), (double v) => v * 8.95054210748189E+27);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareInches), (double v) => v * 1.3873368013333E+35);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareLightYear), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareMeters), (double v) => v * 8.95054210748189E+31);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.Morgen), (double v) => v * 3.58021684299276E+28);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareMiles), (double v) => v * 3.45582362782381E+25);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareNauticalMiles), (double v) => v * 2.60956053215539E+25);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquarePica), (double v) => v * 7.19195397811181E+38);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareLightYear, AreaUnit.SquareYards), (double v) => v * 1.0704759269547E+32);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.InternationalAcre), (double v) => v * 0.000247105381467165);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.USSurveyAcre), (double v) => v * 0.000247104393046628);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareAngstrom), (double v) => v * 1E+20);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.Are), (double v) => v * 0.01);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareFeet), (double v) => v * 10.7639104167097);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.Hectare), (double v) => v * 0.0001);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareInches), (double v) => v * 1550.0031000062);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareLightYear), (double v) => v * 1.11725076312873E-32);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareMeters), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.Morgen), (double v) => v * 0.0004);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareMiles), (double v) => v * 3.86102158542446E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareNauticalMiles), (double v) => v * 2.91553349598123E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquarePica), (double v) => v * 8035216.07043214);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMeters, AreaUnit.SquareYards), (double v) => v * 1.19599004630108);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.InternationalAcre), (double v) => v * 0.617763453667913);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.USSurveyAcre), (double v) => v * 0.61776098261657);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareAngstrom), (double v) => v * 2.5E+23);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.Are), (double v) => v * 25.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareFeet), (double v) => v * 26909.7760417743);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.Hectare), (double v) => v * 0.25);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareInches), (double v) => v * 3875007.7500155);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareLightYear), (double v) => v * 2.79312690782183E-29);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareMeters), (double v) => v * 2500.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.Morgen), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareMiles), (double v) => v * 0.000965255396356115);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareNauticalMiles), (double v) => v * 0.000728883373995307);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquarePica), (double v) => v * 20088040176.0804);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.Morgen, AreaUnit.SquareYards), (double v) => v * 2989.9751157527);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.InternationalAcre), (double v) => v * 640.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.USSurveyAcre), (double v) => v * 639.99744000256);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareAngstrom), (double v) => v * 2.589988110336E+26);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.Are), (double v) => v * 25899.88110336);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareFeet), (double v) => v * 27878400.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.Hectare), (double v) => v * 258.9988110336);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareInches), (double v) => v * 4014489600.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareLightYear), (double v) => v * 2.89366619276724E-26);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareMeters), (double v) => v * 2589988.110336);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.Morgen), (double v) => v * 1035.9952441344);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareMiles), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareNauticalMiles), (double v) => v * 0.755119708987773);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquarePica), (double v) => v * 20811114086400.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareMiles, AreaUnit.SquareYards), (double v) => v * 3097600.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.InternationalAcre), (double v) => v * 847.547736315756);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.USSurveyAcre), (double v) => v * 847.544346128201);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareAngstrom), (double v) => v * 3.429904E+26);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.Are), (double v) => v * 34299.04);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareFeet), (double v) => v * 36919179.3939143);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.Hectare), (double v) => v * 342.9904);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareInches), (double v) => v * 5316361832.72367);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareLightYear), (double v) => v * 3.83206286145829E-26);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareMeters), (double v) => v * 3429904.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.Morgen), (double v) => v * 1371.9616);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareMiles), (double v) => v * 1.32429333799337);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareNauticalMiles), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquarePica), (double v) => v * 27560019740839.5);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareNauticalMiles, AreaUnit.SquareYards), (double v) => v * 4102131.04376826);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.InternationalAcre), (double v) => v * 3.075279859324E-11);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.USSurveyAcre), (double v) => v * 3.07526755821687E-11);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareAngstrom), (double v) => v * 12445216049382.7);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.Are), (double v) => v * 1.24452160493827E-09);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareFeet), (double v) => v * 1.33959190672154E-06);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.Hectare), (double v) => v * 1.24452160493827E-11);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareInches), (double v) => v * 0.000192901234567901);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareLightYear), (double v) => v * 1.39044271284748E-39);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareMeters), (double v) => v * 1.24452160493827E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.Morgen), (double v) => v * 4.97808641975309E-11);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareMiles), (double v) => v * 4.80512478019376E-14);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareNauticalMiles), (double v) => v * 3.62844442566985E-14);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquarePica), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquarePica, AreaUnit.SquareYards), (double v) => v * 1.48843545191282E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.InternationalAcre), (double v) => v * 0.000206611570247934);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.USSurveyAcre), (double v) => v * 0.000206610743802479);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareAngstrom), (double v) => v * 8.3612736E+19);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.Are), (double v) => v * 0.0083612736);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareFeet), (double v) => v * 9.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.Hectare), (double v) => v * 8.3612736E-05);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareInches), (double v) => v * 1296.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareLightYear), (double v) => v * 9.34163931032813E-33);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareMeters), (double v) => v * 0.83612736);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.Morgen), (double v) => v * 0.000334450944);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareMiles), (double v) => v * 3.22830578512397E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareNauticalMiles), (double v) => v * 2.43775732498636E-07);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquarePica), (double v) => v * 6718464.0);
			dictionary.Add(Tuple.Create<AreaUnit, AreaUnit>(AreaUnit.SquareYards, AreaUnit.SquareYards), (double v) => v * 1.0);
			AreaConverter.Lookup = dictionary;
		}

		public static double Convert(double number, AreaUnit from_unit, AreaUnit to_unit)
		{
			if (from_unit != to_unit)
			{
				return AreaConverter.Lookup[Tuple.Create<AreaUnit, AreaUnit>(from_unit, to_unit)](number);
			}
			return number;
		}

		static readonly Dictionary<Tuple<AreaUnit, AreaUnit>, Func<double, double>> Lookup;
	}
}
