using System;
using System.Collections.Generic;

namespace Telerik.Windows.Documents.Spreadsheet.Maths
{
	sealed class DistanceConverter
	{
		static DistanceConverter()
		{
			Dictionary<Tuple<DistanceUnit, DistanceUnit>, Func<double, double>> dictionary = new Dictionary<Tuple<DistanceUnit, DistanceUnit>, Func<double, double>>();
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Angstrom), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Ell), (double v) => v * 8.74890638670166E-11);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Foot), (double v) => v * 3.28083989501312E-10);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Inch), (double v) => v * 3.93700787401575E-09);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.LightYear), (double v) => v * 1.05700083402462E-26);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Meter), (double v) => v * 1E-10);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.NauticalMile), (double v) => v * 5.39956803455724E-14);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Parsec), (double v) => v * 3.24077928966473E-27);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Pica6), (double v) => v * 2.36220472440945E-08);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Pica72), (double v) => v * 2.83464566929134E-07);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.StatuteMile), (double v) => v * 6.21371192237334E-14);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.SurveyMile), (double v) => v * 6.21369949494949E-14);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Angstrom, DistanceUnit.Yard), (double v) => v * 1.09361329833771E-10);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Angstrom), (double v) => v * 11430000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Ell), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Foot), (double v) => v * 3.75);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Inch), (double v) => v * 45.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.LightYear), (double v) => v * 1.20815195329014E-16);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Meter), (double v) => v * 1.143);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.NauticalMile), (double v) => v * 0.000617170626349892);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Parsec), (double v) => v * 3.70421072808678E-17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Pica6), (double v) => v * 270.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Pica72), (double v) => v * 3240.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.StatuteMile), (double v) => v * 0.000710227272727273);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.SurveyMile), (double v) => v * 0.000710225852272727);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Ell, DistanceUnit.Yard), (double v) => v * 1.25);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Angstrom), (double v) => v * 3048000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Ell), (double v) => v * 0.266666666666667);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Foot), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Inch), (double v) => v * 12.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.LightYear), (double v) => v * 3.22173854210703E-17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Meter), (double v) => v * 0.3048);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.NauticalMile), (double v) => v * 0.000164578833693305);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Parsec), (double v) => v * 9.87789527489808E-18);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Pica6), (double v) => v * 72.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Pica72), (double v) => v * 864.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.StatuteMile), (double v) => v * 0.000189393939393939);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.SurveyMile), (double v) => v * 0.000189393560606061);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Foot, DistanceUnit.Yard), (double v) => v * 0.333333333333333);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Angstrom), (double v) => v * 254000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Ell), (double v) => v * 0.0222222222222222);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Foot), (double v) => v * 0.0833333333333333);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Inch), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.LightYear), (double v) => v * 2.68478211842252E-18);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Meter), (double v) => v * 0.0254);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.NauticalMile), (double v) => v * 1.37149028077754E-05);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Parsec), (double v) => v * 8.2315793957484E-19);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Pica6), (double v) => v * 6.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Pica72), (double v) => v * 72.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.StatuteMile), (double v) => v * 1.57828282828283E-05);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.SurveyMile), (double v) => v * 1.57827967171717E-05);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Inch, DistanceUnit.Yard), (double v) => v * 0.0277777777777778);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Angstrom), (double v) => v * 9.4607304725808E+25);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Ell), (double v) => v * 8277104525442520.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Foot), (double v) => v * 31039141970409500.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Inch), (double v) => v * 3.72469703644913E+17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.LightYear), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Meter), (double v) => v * 9460730472580800.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.NauticalMile), (double v) => v * 5108385784330.89);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Parsec), (double v) => v * 0.306601393806398);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Pica6), (double v) => v * 2.23481822186948E+18);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Pica72), (double v) => v * 2.68178186624338E+19);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.StatuteMile), (double v) => v * 5878625373183.61);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.SurveyMile), (double v) => v * 5878613615932.86);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.LightYear, DistanceUnit.Yard), (double v) => v * 10346380656803200.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Angstrom), (double v) => v * 10000000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Ell), (double v) => v * 0.874890638670166);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Foot), (double v) => v * 3.28083989501312);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Inch), (double v) => v * 39.3700787401575);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.LightYear), (double v) => v * 1.05700083402462E-16);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Meter), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.NauticalMile), (double v) => v * 0.000539956803455724);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Parsec), (double v) => v * 3.24077928966473E-17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Pica6), (double v) => v * 236.220472440945);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Pica72), (double v) => v * 2834.64566929134);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.StatuteMile), (double v) => v * 0.000621371192237334);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.SurveyMile), (double v) => v * 0.00062136994949495);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Meter, DistanceUnit.Yard), (double v) => v * 1.09361329833771);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Angstrom), (double v) => v * 18520000000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Ell), (double v) => v * 1620.29746281715);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Foot), (double v) => v * 6076.1154855643);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Inch), (double v) => v * 72913.3858267717);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.LightYear), (double v) => v * 1.95756554461359E-13);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Meter), (double v) => v * 1852.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.NauticalMile), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Parsec), (double v) => v * 6.00192324445907E-14);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Pica6), (double v) => v * 437480.31496063);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Pica72), (double v) => v * 5249763.77952756);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.StatuteMile), (double v) => v * 1.15077944802354);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.SurveyMile), (double v) => v * 1.15077714646465);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.NauticalMile, DistanceUnit.Yard), (double v) => v * 2025.37182852143);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Angstrom), (double v) => v * 3.08567758128155E+26);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Ell), (double v) => v * 26996304298176300.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Foot), (double v) => v * 1.01236141118161E+17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Inch), (double v) => v * 1.21483369341793E+18);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.LightYear), (double v) => v * 3.26156377694566);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Meter), (double v) => v * 30856775812815500.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.NauticalMile), (double v) => v * 16661326032837.8);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Parsec), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Pica6), (double v) => v * 7.28900216050761E+18);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Pica72), (double v) => v * 8.74680259260913E+19);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.StatuteMile), (double v) => v * 19173511575409.3);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.SurveyMile), (double v) => v * 19173473228386.2);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Parsec, DistanceUnit.Yard), (double v) => v * 33745380372720400.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Angstrom), (double v) => v * 42333333.3333333);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Ell), (double v) => v * 0.0037037037037037);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Foot), (double v) => v * 0.0138888888888889);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Inch), (double v) => v * 0.166666666666667);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.LightYear), (double v) => v * 4.47463686403754E-19);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Meter), (double v) => v * 0.00423333333333333);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.NauticalMile), (double v) => v * 2.28581713462923E-06);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Parsec), (double v) => v * 1.3719298992914E-19);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Pica6), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Pica72), (double v) => v * 12.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.StatuteMile), (double v) => v * 2.63047138047138E-06);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.SurveyMile), (double v) => v * 2.63046611952862E-06);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica6, DistanceUnit.Yard), (double v) => v * 0.00462962962962963);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Angstrom), (double v) => v * 3527777.77777778);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Ell), (double v) => v * 0.000308641975308642);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Foot), (double v) => v * 0.00115740740740741);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Inch), (double v) => v * 0.0138888888888889);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.LightYear), (double v) => v * 3.72886405336462E-20);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Meter), (double v) => v * 0.000352777777777778);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.NauticalMile), (double v) => v * 1.90484761219102E-07);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Parsec), (double v) => v * 1.14327491607617E-20);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Pica6), (double v) => v * 0.0833333333333333);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Pica72), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.StatuteMile), (double v) => v * 2.19205948372615E-07);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.SurveyMile), (double v) => v * 2.19205509960718E-07);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Pica72, DistanceUnit.Yard), (double v) => v * 0.000385802469135803);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Angstrom), (double v) => v * 16093440000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Ell), (double v) => v * 1408.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Foot), (double v) => v * 5280.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Inch), (double v) => v * 63360.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.LightYear), (double v) => v * 1.70107795023251E-13);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Meter), (double v) => v * 1609.344);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.NauticalMile), (double v) => v * 0.868976241900648);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Parsec), (double v) => v * 5.21552870514619E-14);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Pica6), (double v) => v * 380160.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Pica72), (double v) => v * 4561920.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.StatuteMile), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.SurveyMile), (double v) => v * 0.999998);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.StatuteMile, DistanceUnit.Yard), (double v) => v * 1760.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Angstrom), (double v) => v * 16093472186944.4);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Ell), (double v) => v * 1408.00281600563);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Foot), (double v) => v * 5280.01056002112);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Inch), (double v) => v * 63360.1267202534);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.LightYear), (double v) => v * 1.70108135239522E-13);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Meter), (double v) => v * 1609.34721869444);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.NauticalMile), (double v) => v * 0.868977979856608);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Parsec), (double v) => v * 5.21553913622446E-14);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Pica6), (double v) => v * 380160.760321521);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Pica72), (double v) => v * 4561929.12385825);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.StatuteMile), (double v) => v * 1.000002000004);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.SurveyMile), (double v) => v * 1.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.SurveyMile, DistanceUnit.Yard), (double v) => v * 1760.00352000704);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Angstrom), (double v) => v * 9144000000.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Ell), (double v) => v * 0.8);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Foot), (double v) => v * 3.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Inch), (double v) => v * 36.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.LightYear), (double v) => v * 9.66521562632108E-17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Meter), (double v) => v * 0.9144);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.NauticalMile), (double v) => v * 0.000493736501079914);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Parsec), (double v) => v * 2.96336858246942E-17);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Pica6), (double v) => v * 216.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Pica72), (double v) => v * 2592.0);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.StatuteMile), (double v) => v * 0.000568181818181818);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.SurveyMile), (double v) => v * 0.000568180681818182);
			dictionary.Add(Tuple.Create<DistanceUnit, DistanceUnit>(DistanceUnit.Yard, DistanceUnit.Yard), (double v) => v * 1.0);
			DistanceConverter.Lookup = dictionary;
		}

		public static double Convert(double number, DistanceUnit from_unit, DistanceUnit to_unit)
		{
			if (from_unit != to_unit)
			{
				return DistanceConverter.Lookup[Tuple.Create<DistanceUnit, DistanceUnit>(from_unit, to_unit)](number);
			}
			return number;
		}

		static readonly Dictionary<Tuple<DistanceUnit, DistanceUnit>, Func<double, double>> Lookup;
	}
}
