using System;

namespace Telerik.Windows.Documents.Licensing
{
	//static class TrialMessages
	//{
	//	internal static readonly string DocumentProcessingTrialMessage = "This document was generated by a trial version of Telerik Document Processing.";

	//	internal static readonly string DocumentProcessingUnlicencedMessage = "This document was generated by a copy of Telerik Document Processing licensed for use only by MyApp.";
	//}
}
